.na
.nh
.TH alignlog 1 2.6.0 BL3DEMC
.SH NAME
alignlog - extract data from tiltalign log file
.SH SYNOPSIS
alignlog <options> [a | b | log_filename]
.SH DESCRIPTION
This shell script extracts useful sections from the output of tiltalign(1).
One or more options may be entered in any order; if multiple options are given,
the different sections are printed out in the order given.  If no filename is
entered, alignlog will attempt to extract sections from the file align.log.
If a or b is entered instead of a filename after the options, then sections
will be printed from aligna.log or alignb.log, respectively.
.SS Options
.TP
.B -m
Mappings: print variable mappings.
.TP
.B -e
Errors: print errors and ratio of measured to unknowns.
.TP
.B -s
Solution: print the alignment solution for each view.
.TP
.B -l
Local: print the location and size of each local area, the number
of fiducials on each surface, and the mean residual.
.TP
.B -c
Coordinates: print the 3-D coordinates of the fiducials.
.TP
.B -r
Residuals: print large residuals.
.TP
.B -a
Angles: print planar fits and recommended change in angles.
.TP
.B -b
Beam tilt: print F values from beam tilt search

.SH EXAMPLES
Print solutions and errors from align.log:
    alignlog -s -e

Print 3-D coordinates and angle recommendations from alignb.log:
    alignlog -c -a b
.SH AUTHOR
David Mastronarde,  mast@colorado.edu
.SH SEE ALSO
tiltalign(1)
.SH BUGS
