#!/bin/csh -f

set version = `cat ../.version`

which nroff
if ($status) then
    echo nroff not on path
    exit 1
endif

# test for -c option, needed starting in Red Hat 8
set copt = "-c"
echo junk | nroff -c >& /dev/null
if ($status) set copt = ""

foreach i (*.man)
	echo "converting $i to ${i:r}.1"
	sed "/^\.TH/s/ [0-9]\.[0-9\.]* / $version /" $i | nroff -man $copt >! ${i:r}.1
end

foreach j (*.1)
	echo "converting $j to ${j:r}.html"
	$argv[1]/mantohtml < $j >! ${j:r}.html
end


exit

