#!/usr/bin/python -u
# csvtohtml - converts csv file to html table
# The csv file must start with a title row, an html header row, and a table header row
#
# Author: David Mastronarde
#
# $Id$

# Find index of last non-empty string in the row
def lastNonEmptyIndex(row):
   last = -1;
   for ind in range(len(row)):
      if len(row[ind]):
         last = ind
   return last

import csv, sys
sys.path.append('../pysrc')
from imodpy import *

insertTag = 'INSERT CSV FILE'

if len(sys.argv) < 3:
   prnstr('Usage: csvtohtml csv_file output_file [insert_into_file]')
   prnstr('       insert_into_file must have all HTML starting and ending codes')
   prnstr('       and a line with just ' + insertTag + ' on it')
   sys.exit(1)

insertLines = []
if len(sys.argv) > 3:
   insertLines = readTextFile(sys.argv[3])

csvfile = open(sys.argv[1], 'r')
reader = csv.reader(csvfile)
needTitle = True
needHeader = True
needTableHead = True
lastBlank = False
outlines = []

if insertLines:
   for insertInd in range(len(insertLines)):
      if insertTag in insertLines[insertInd].strip():
         break
      outlines.append(insertLines[insertInd])
   else:   # ELSE ON FOR
      prnstr('ERROR: Could not find a line with ' + insertTag + ' in ' + sys.argv[3])
      sys.exit(1)

   needTitle = False
   insertInd += 1
   
else:
   outlines = ['<HTML>',
               '<HEAD>']

inrows = []
maxlen = 0
for row in reader:
   inrows.append(row)
   maxlen = max(maxlen, len(row))

for row in inrows:
   lastNonEmpty = lastNonEmptyIndex(row)
   tdtag = 'TD'
   if needTitle:
      if lastNonEmpty < 0:
         continue
      outlines += ['<TITLE>' + row[0] + '</TITLE>',
                   '</HEAD>',
                   '<BODY>',
                   '<A NAME = "TOP">']
      needTitle = False
      continue

   elif needHeader:
      if lastNonEmpty < 0:
         continue
      outlines += ['<H2 ALIGN=center>' + row[0] + '</H2>',
                   '<TABLE BORDER COLS=2>',
                   '<THEAD>']
      needHeader = False
      continue
   
   elif needTableHead:
      if lastNonEmpty < 0:
         continue
      tdtag = 'TH'

   line = '<TR>'
   for ind in range(maxlen):
      if ind <= lastNonEmpty:
         cell = row[ind]
      else:
         cell = ''
      if cell == '':
         cell = '&nbsp;'
      if lastBlank and lastNonEmpty == 0 and ind == 0:
         line += fmtstr('<{}><B>{}</B></{}>', tdtag, cell, tdtag)
      else:
         line += fmtstr('<{}>{}</{}>', tdtag, cell, tdtag)
   line += '</TR>'
   outlines.append(line)
   lastBlank = lastNonEmpty < 0
   if needTableHead:
      outlines += ['</THEAD>',
                    '<TBODY>']
      needTableHead = False

outlines += ['</TBODY>',
             '</TABLE>']

if insertLines:
   outlines += insertLines[insertInd:]
else:
   outlines += ['</BODY>',
                '</HTML>']

writeTextFile(sys.argv[2], outlines)
sys.exit(0)
