.na
.nh
.TH dm2mrc 1 2.6.3 BL3DEMC
.SH NAME
dm2mrc \- Create an MRC image stack from Digital Micrograph files.
.SH SYNOPSIS
dm2mrc [-d] <DM files...> <mrc image file>
.SH DESCRIPTION
dm2mrc will convert Digital Micrograph (DM) image files to an MRC stack,
using raw2mrc(1).  The program should be able to convert version DM 2.5 files
produced by DM 2.5 running on a Macintosh, DM 2.5 files exported by DM 3
running on a Windows PC, and DM 3 files produced on a PC.  
.P
There is a single
option,
.B -d,
which can be used to indicate that the input files are different in some 
respect and should be treated independently.
Without this option, dm2mrc will examine the first input file to 
determine the version of DM file, the data type, the image dimensions, and
the header offset to the beginning of the data in the file.  It will then
assume that these same attributes apply to the rest of the input files, and
run raw2mrc(1) in one step on all of the files.  If any of these attributes 
might vary among the input files, or if the file sizes are not all identical,
use the 
.B -d
option.  The program will then scan through all of the files to determine these
attributes, convert each one independently into a temporary file, then
make a stack from the temporary files with newstack(1).
.P
The program will convert signed 2-byte integers, unsigned 2-byte integers
(by subtracting 32767), signed bytes (by adding 127), unsigned bytes, and
4-byte floating point numbers or integers (producing floating point output).
.SH AUTHOR
David Mastronarde
.SH SEE ALSO
raw2mrc(2), newstack(2)
.SH BUGS
The program has been written to handle common examples generated on
a small subset of Digital Micrograph versions, so it could easily fail with
files outside the range of this experience.
Email reports of problems to mast@colorado.edu.
