.na
.nh
.TH FROMMRC 1 2.00 BL3DEMC
.SH NAME
frommrc \- Converts a mrc file to SGI rgb image files.
.SH SYNOPSIS
frommrc [mrc filename] [rgb filename]
.SH DESCRIPTION
A series of rgb files will be created with the prefix 
[rgb filename] and with the suffix nnn.rgb,
where nnn is the z number.
.PP
If z for the mrc file is equal to 1 no suffix is
added to the rgb filename.
.PP
The image is automatically scaled so that the minimum
and maximum are 0 and 255 respectivily if the image
is more than 8-bits deep.
.PP
Color MRC images are translated directly.  The color
format for MRC is not standard.  The mode number
is 16 and the data is stored as three bytes;
red, green and blue.


.SH AUTHOR
Jim Kremer 

.SH SEE ALSO
rgbv    View SGI rgb files.
.br
tomrc   Convert MRC image files to SGI rgb image files.

.SH BUGS
Email bug reports to mast@colorado.edu.
