.na
.nh
.TH imodinfo 1 2.30 BL3DEMC
.SH NAME
imodinfo \- Prints information about IMOD files.
.SH SYNOPSIS
imodinfo [options] <IMOD filename>
.SH DESCRIPTION
Prints to standard output information about an IMOD model
given as the input filename.
Types of information output varies, depending upon the options.
Typical uses include printing out 
lists of objects, contours and
point data in an IMOD file; 
printing out area, lengths and centroids of contours;
and printing out surface area and volume of objects.

The options 
.B -a
, 
.B -c
, 
.B -l
, 
.B -o
,
.B -p
, 
.B -r
and 
.B -s 
are mutually exclusive.
.SS Options
.TP
.B -a
Print ascii readable IMOD output. Not all of the types
of data stored in a binary model are printed in an ascii
model file, but all contour and mesh data are printed.
.TP
.B -c
Print area of object in column output.
.TP
.B -l
Print lengths of open contours in column output.
.TP
.B -s
Print volumes and surface areas for each separate surface in an object.
.TP
.B -p
Print point size information, including a summary of mean radius, and the
implied total surface area and volume of scattered points.
.TP
.B -r
Print ratio of length to area for closed contours.
.TP
.B -o <object #>
Print full report on given object #.  The volumes will not be correct if there
are inside contours, and clipped volumes are not quite as accurate as with the
.B
-t 
option.
.TP
.B -i
Analyze for inside contours and adjust computed volume by subtracting
rather than adding the areas of contours that represent inside-out surfaces.
This option works only for closed contours and only with the standard output,
not with the
.B -s
or
.B -o
options.  Individual contour data will not be printed for closed contour 
objects.
.TP 
.B -x <min,max>
.TP
.B -y <min,max>
.TP
.B -z <min,max>
Compute areas and volumes within the subvolume specified by the minimum and
maximum values.  One or two of these three options may be entered if
desired.  Subvolume analysis works only with closed contour and scattered
point objects, and only with the standard output or the 
.B -p
option.  In the standard output, the number of scattered points within 
the subvolume will be reported for each object.  If you use either the
.B -x
or
.B -y
option, the program will automatically analyze for inside contours and behave 
the same as if the
.B -i
option were selected.
.TP
.B -t <1/-1>
Truncate objects by their respective clipping planes; enter 
.B -t 1
or
.B -t -1
to use the clipping plane in its normal or inverted orientation.  
Like the subvolume analysis, this option
works only with closed contour and scattered
point objects, and only with the standard output or the
.B -p
option.
With this option, the program will automatically analyze for inside contours.
Clipping plane truncation
can be used together with subvolume analysis.
.TP
.B -v[v]
Print more verbose output. The 
.B -vv
option will increase the level of output information even further.  These 
options override the
.B -h
option.
.TP
.B -h
Suppress the information about each contour in the standard model output.
Use this option to extract summary information more easily from large models.
.TP
.B -f <filename>
Write output to given filename instead of the screen.
.SH AUTHORS
.nf
Jim Kremer 
David Mastronarde
.fi
.SH SEE ALSO
3dmod(1)
.SH BUGS
Cylinder surface areas are erroneous because they do not account for the 
obliquity of the surface; for a sphere the area will be underestimated by
22%.  Use mesh surface areas whenever possible.

Email bug reports to mast@colorado.edu.
