.na
.nh
.TH imodexplode 1 2.20 BL3DEMC
.SH NAME
imodexplode \- Make an exploded model by shifting objects.
.SH SYNOPSIS
imodexplode -o objects -x DX -y DY -z DZ ... input_model output_model
.SH DESCRIPTION
Makes an "exploded" model by shifting individual objects by specified amounts.
The option list can consist of a series of entries, each specifying a list of
objects and the displacements DX, DY, and DZ by which to shift them.
Following a
.B -o
flag, place a list of object numbers;
this list
can consist of comma-separated ranges of object numbers, for example
1-3,6-9,13,15.  After the list of objects, specify the shift for those objects
with the -x, -y, and/or -z flags.  If the shift is along one axis, only the
shift for that axis needs to be enter; in other words, there is no need to 
enter zero shifts for the other axes.

.SH AUTHOR
David Mastronarde,  mast@colorado.edu
.SH SEE ALSO
3dmod(1)
.SH BUGS
