.na
.nh
.TH imod2rib 1 2.00 BL3DEMC
.SH NAME
imod2rib \- Make a RIB model from an IMOD model file.
.SH SYNOPSIS
imod2rib [options] <IMOD model> <meta model>
.SH DESCRIPTION
Convert an IMOD model file to the RIB file format used
by Pixar's Renderman Interface.  The model will have similar attributes
set by those seen in 3dmodv.

The Renderman (R) Interface Procedures and RIB Protocol are:
Copyright 1988,1989, Pixar.
All rights reseved.
RenderMan (R) is a registered trademark of Pixar.
 
.SS Options
None
.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
.SH BUGS
Email bug reports to mast@colorado.edu.
