.na
.nh
.TH imodsortsurf 1 2.20 BL3DEMC
.SH NAME
imodsortsurf \- Sort contours into surfaces based on mesh.
.SH SYNOPSIS
imodsortsurf [-o objects ] <input model> <output model>
.SH DESCRIPTION
Uses the mesh produced by imodmesh to analyze the connections between contours,
and assigns each set of connected contours a separate surface number.
The analysis will be performed on all objects unless the 
.B -o
option is used.  With the 
.B -o
option, followed by a list of objects,
only the objects in the given list will be analyzed.  The list
can consist of comma-separated ranges of object numbers, for example
1-3,6-9,13,15.

If one desires to have each surface be in a separate object so that they
can be colored differently, it is easy to load the model into 3dmod and
move all of the contours with a given surface number into a separate object.
Use the Edit - Contour - Move menu item, and check the box "Move all contours 
with the same surface #."

.SH AUTHOR
David Mastronarde,  mast@colorado.edu
.SH SEE ALSO
imodmesh(1), 3dmod(1)
.SH BUGS
