.na
.nh
.TH imodcmopp 1 2.00 BL3DEMC
.SH NAME
imodcmopp \- color model paint and project a tomogram.
.SH SYNOPSIS
imodcmopp <IMOD contour model> <mrc image> <mrc output file> [options]
.SH DESCRIPTION
imodcmopp makes a color mrc tilt file from different projected
views of tomographic image data contained inside of model
contours.  The model must be in IMOD format and the
tomogram must be in mrc format.
The movie file is in mrc color format. Use the program
frommrc to convert to sgi rgb files.
.SS Options
.TP
.B -x | -z
The 
.B -x 
and 
.B -z 
options are used to change the axis that the 
tilt series will rotate about. The y axis is the default.   
.TP
.B -n
The 
.B -n 
option makes the x and y output size to be large 
enough to fill an NTSC sized window.
.TP
.B -t <first,end,increment>
The 
.B -t 
option is used to change the range and increments in
tilts for the movie.  The default is 
.B -t 0,175,5 
where 0 
degrees is the starting tilt, 175 is the ending tilt and 5 
degrees is the step between the tilts.
.TP
.B -T <tempdir>
imodcmopp creates several temporary files, the defalut directory is
the current working directory, but this option can override this setting.
.SH CAVEATS
imodcmopp needs to have the command xyzproj	in the path in order 
to work.
.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
imodmop, xyzproj, frommrc.
.SH BUGS
The model Z scale information is ignored.
Only available for UNIX machines.
Email bug reports to mast@colorado.edu.
