.na
.nh
.TH imodextract 1 2.20 BL3DEMC
.SH NAME
imodextract \- Extract objects from a model into a new model.
.SH SYNOPSIS
imodextract  list_of_objects  input_model  output_model
.SH DESCRIPTION
Extracts a subset of the objects from an IMOD model and places them into a new 
model.  This can be much more convenient than making a copy of a model and 
deleting objects one by one inside 3dmod.  The list of object numbers
can consist of comma-separated ranges of numbers, for example
1-3,6-9,13,15.
.SH AUTHOR
David Mastronarde,  mast@colorado.edu
.SH SEE ALSO
3dmod(1)
.SH BUGS
