.na
.nh
.TH imod2meta 1 2.00 BL3DEMC
.SH NAME
imod2meta \- Make a 3D META model from an IMOD model file.
.SH SYNOPSIS
imod2meta  [options]  IMOD_model  meta_model
.SH DESCRIPTION
Convert an IMOD model file to the meta file format used
by QuickDraw 3D.  The model will have similar attributes
set by those seen in 3dmodv. 
.SH OPTIONS
None
.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
.SH BUGS
Email bug reports to mast@colorado.edu.
