.na
.nh
.TH imodsendevent 1 2.7.2 BL3DEMC
.SH NAME
imodsendevent \- Sends an X event with a command to 3dmod
.SH SYNOPSIS
imodsendevent Window_ID action [text_string]
.SH DESCRIPTION
This program will send a command to 3dmod(1) to perform an action.  It takes
two or three arguments.  The first
argument is a window ID, which can be obtained by starting
imod with the 
.B -W
option.  The second argument is a numeric code for an action.  The third is
an optional text string, such as the name of a model file when opening a 
model.
.P
Currently, 3dmod will accept 8 commands:
   1  Open model file (follow with file name)
   2  Save model file
   3  Open model view window
   4  Quit 3dmod
   5  Raise windows (bring all windows to the front)
   6  Switch to model or movie mode (follow with 0 for movie mode, a 
         nonzero number or nothing for model mode)
   7  Open model file but keep current black/white levels (follow with
         file)
   8  Open Bead Fixer window or raise it if already open
.SH AUTHOR
David Mastronarde,  mast@colorado.edu
.SH SEE ALSO
3dmod(1)
.SH BUGS
