.na
.nh
.TH imodmop 1 2.00 BL3DEMC
.SH NAME
imodmop -\ paint an IMOD model with image data.
.SH SYNOPSIS
imodmop [options] <model> <image> <output file>
.SH DESCRIPTION
Mop stands for MOdel Painter,  It colors in data inside
of model contours.  If a contours object type is outside
then mop erases all data inside of that contour.
.SS Options
.TP
.B -h
print help
.TP
.B -r
Scale output by red model value.
.B -g
Scale output by green model value.
.B -b
Scale output by blue model value.
.P
Model file is an IMOD model file.
Input image is an mrc 3-D image file.
Output image is the image data inside of the model.
.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
3dmod, cmopp, xyzproj
.SH BUGS
Email bug reports to mast@colorado.edu.
