.na
.nh
.TH mrc2tif 1 2.00 BL3DFS
.SH NAME
mrc2tif \- Create a series of TIFF image files from an MRC image file.
.SH SYNOPSIS
mrc2tif [options] <mrc file> <tiff file root name>
.SH DESCRIPTION
mrc2tif creates a series of TIFF files with the prefix [tiff root name]
and with the suffex nnn.tif, where nnn is the z number.


.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
clip, newstack
.SH BUGS
Complex and float data modes are not supported.
16 bit grayscale images (MRC mode 1) haven't been tested.

Email bug reports to mast@colorado.edu.
