.na
.nh
.TH mrc2tif 1 2.00 BL3DEMC
.SH NAME
mrc2tif \- Create a series of TIFF image files from an MRC image file.
.SH SYNOPSIS
mrc2tif [options] <mrc file> <tiff file root name>
.SH DESCRIPTION
mrc2tif creates a series of TIFF files with the prefix [tiff root name]
and with the suffix nnn.tif, where nnn is the z number.  Byte, 16-bit integer,
and RGB color files (modes 0, 1, 16) can be converted.


.SH AUTHORS
Jim Kremer, David Mastronarde
.SH SEE ALSO
clip, newstack
.SH BUGS
Complex and float data modes are not supported.

Email bug reports to mast@colorado.edu.
