.na
.nh
.TH newst 1 2.30 BL3DEMC
.SH NAME
newst \- Front end to the newstack program.
.SH SYNOPSIS
newst [options] <input file(s)>  <output file>
.SH DESCRIPTION
newst used to provide a command-line interface to newstack, but was retired
after newstack was converted to take command-line input.
Newstack accepts all of the options that newst did.  See the man page for
newstack(1) for details.
