.na
.nh
.TH onepatchcorr 1 2.50 BL3DEMC
.SH NAME
onepatchcorr \- Correlate a patch from two volumes at one position
.SH SYNOPSIS
onepatchcorr xsize ysize zsize  xcen ycen zcen  filea fileb  output_file
.SH DESCRIPTION
onepatchcorr is a C-shell script to determine the 3-D displacement
between a single subset or patch extracted from two image volumes in
filea and fileb.  It extracts the patch from each of the two 
volumes using tapervoledge.  It then uses clip to do 3-D cross-correlation
between the patches and determines the displacement of the patch in fileb
relative to the patch in filea.  
It writes a single line to the output file giving the
displacement between the two files in X, Y, and Z.

.SH ARGUMENTS
The size of the patch in X, Y, and Z is set by the arguments xsize, ysize, 
and zsize.

The location of the center of the patch is given by the index coordinates
xcen, ycen, and zcen.

.SH AUTHOR
David Mastronarde  <mast@colorado.edu>
.SH SEE ALSO
tapervoledge(1), clip(1)
