.na
.nh
.TH rec2imod 1 2.00 BL3DEMC
.SH NAME
rec2imod \- Make an IMOD model file from a HVEM 3D recon file.
.SH SYNOPSIS
rec2imod  [options]  hvem_rec_file  imod_model
.SH DESCRIPTION
HVEM 3D was a DOS program used to reconstruct 3D models from serial sections.
rec2imod will take the .rec files created on a PC and convert them to
an IMOD model.
.SH OPTIONS
.TP
.B -m \fIvalue\fR
Sets the magnification in thousands of times magnification. (kx).
.TP
.B -t \fIvalue\fR
The thickness of each section given in um.
.TP
.B -p \fIvalue\fR
Sets the pixel size in mm of the model coordinates, the default value
is 0.1mm.
.TP
.B -z \fIvalue\fR
Sets the zscale of the model, the default value is 1.0.
.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
.SH BUGS

Email bug reports to mast@colorado.edu.
