.na
.nh
.TH tif2mrc 1 2.6.0 BL3DEMC
.SH NAME
tif2mrc \- Make a MRC file from tiff image files.
.SH SYNOPSIS
tif2mrc [-g | -u | -d] [-b file] <tiff files...> <MRC file>
.SH DESCRIPTION
tif2mrc takes a series of tiff files and converts them
into an MRC stack.  The x and y dimensions of the stack
are the x and y size of the first image.  
tif2mrc can also convert a single multi-page tiff file to an MRC stack.
.P
Images need not all be the same size if they are 8-bit grayscale.
Images that are larger will be clipped, and images that
are smaller will be placed in one corner of the larger area with a gray border.
It is recommended that only images of the same size be used.
.SS Options
.TP
.B -g
This
option will convert 24-bit color images to 8-bit grayscale in the MRC stack.
.TP
.B -u
With this option, the program will convert 16-bit numbers from unsigned to
signed integers by subtracting 32768.
By default, 16-bit numbers are considered signed integers, because
that is the way that such numbers are treated in an MRC file of mode 1.
Use this option if the tiff files have positive numbers ranging above 32767
and you do not want to lose any of the dynamic range of the numbers.
.TP
.B -d
With this option, the program will treat 16-bit numbers as unsigned integers
and divide them by two.  The resulting numbers will range between 0 and 32767.
Use this option if the tiff files have positive numbers ranging above 32767,
you want the numbers to remain positive,
and you do not mind losing one bit of precision.
.TP 
.B -b file
This option loads a background file in tiff format.
If a background file is loaded its values are subtracted from
the values in the rest of the files.
The background file must have the same data type as the images from which
it is being subtracted (8-bit or 16-bit grayscale).
.SH FILES
If the output file already exists, it will be made a backup file by adding ~
to its name.
.SH AUTHORS
Jim Kremer and David Mastronarde
.SH SEE ALSO
tomrc(1), raw2mrc(1)
.SH BUGS
Only grayscale and color image files are supported; images with color palettes
may not be read correctly.
Grayscale images must be 8 or 16 bit grayscale.
Color images must be 24 bit with pixels stored as 
red-green-blue triplets.
If a standard tiff library is not installed, images must be uncompressed and
must consist of strips rather than tiles.

Email bug reports to mast@colorado.edu.
