.na
.nh
.TH tomrc 1 2.00 BL3DEMC
.SH NAME
tomrc \- Make a mrc file from rgb image files.
.SH SYNOPSIS
tomrc [options] <input files...> <output image>
.SH DESCRIPTION
tomrc takes a series of rgb files and converts them
into an mrc stack.  The default x and y dimensions
are the x and y size of the first image.  Images
that are larger will be clipped, and images that
are smaller will be centered by a black border.
.SS Options
.TP
.B -x <width>
Change the default width of the output image.
.TP
.B -y <height>
Change the default height of the output image.
.TP
.B -c
Make the output file a color file.
The default is to convert and color images to black
and white using the rule gray level =
(red * 0.3) + (green * 0.59) + (blue * 0.11).
.SH AUTHOR
Jim Kremer 
.SH SEE ALSO
frommrc(1)
.SH BUGS
The color output files are not standard MRC files.
They are created with a mode of 16 and store the color
information in three unsigned bytes.

Email bug reports to mast@colorado.edu.
