.na
.nh
.TH trimvol 1 2.30 BL3DEMC
.SH NAME
trimvol \- Trim a volume and scale it to bytes.
.SH SYNOPSIS
trimvol [options] <input file>  <output file>
.SH DESCRIPTION
trimvol provides a command-line interface to the programs findcontrast and
newstack, for copying a selected portion of an MRC image volume into a new
file, with automatic scaling to bytes.
There are options for specifying the volume to be extracted, and for 
controlling the scaling to bytes.
By default, coordinates are numbered from 1.
.SS Options
You can enter either
.B -c
or
.B -s
but not both.  Similarly, you cannot enter both
.B -x
and
.B -nx,
both
.B -y
and
.B -ny,
or both
.B -z
and
.B -nz.
.TP
.B -x <X0,X1>
Copy pixels in X between X0 and X1, inclusive.
.TP
.B -y <Y0,Y1>
Copy pixels in Y between Y0 and Y1, inclusive.
.TP
.B -z <Z0,Z1>
Copy pixels in Z between Z0 and Z1, inclusive.
.TP
.B -nx <size>
Copy "size" pixels in the X dimension, centered on the middle in X.
.TP
.B -ny <size>
Copy "size" pixels in the Y dimension, centered on the middle in Y.
.TP
.B -nz <size>
Copy "size" pixels in the Z dimension, centered on the middle in Z.
.TP
.B -s <S0,S1>
Scale to bytes, determining the optimal scaling to bytes by analyzing
intensities from sections S0 to S1, inclusive, in the flipped volume.
This option runs findcontrast on the specified sections, omitting regions
within 10% of the lateral borders of each section.  A scaling is
chosen which saturates the intensities of one pixel per slice, on average, at
the dark and the light end.
.TP
.B -c <black,white>
Scale to bytes, with relative intensities between "black" and "white" (on a
scale of 0 to 255) stretched to occupy the full range of byte values.
.TP
.B -yz
Flip Y and Z in the output volume by first creating a temporary trimmed volume
with newstack then running "clip flipyz" on this volume to create the final
output file.
.TP
.B -i
Interpret 
.B -x,
.B -y,
and
.B -z
entries as index coordinates numbered from 0, rather than as 3dmod coordinates
numbered from 1.
.TP
.B -f
Interpret
.B -y,
.B -z,
.B -ny,
and
.B -nz
entries as referring to a flipped volume, with Y and Z transposed.
.TP 
.B -P
Output process ID.
.SH FILES
If the output file already exists a backup image
of the original is created
with the ~ extension.
.SH AUTHOR
David Mastronarde  <mast@colorado.edu>
.SH SEE ALSO
newstack(1), findcontrast(1)
