.TH uitestadoc 1 2.7 BL3DEMC
.na
.nh

.SH NAME
uitest.adoc \- Description of user interface tests

.SH SYNOPSIS
.nf
.B $IMOD_UITEST_SOURCE/uitest.adoc
.B cd \fIthe_run_directory
.B uitest \fITest_section_name
.fi

.SH DESCRIPTION
The uitest.adoc file contains a master list of tests of the Etomo user
interface and set up information for each test.  Any section
type or attribute name not listed below will be ignored during testing.
A test can be run by running \fBuitest\fR with the name of the Test section
desired (See \fBTest Section and Attributes\fR).  The test will run under a directory
called UITests, which will be created in the run directory if it doesn't exist.

.SS Environment Variables

.TP
.B IMOD_UITEST_SOURCE
Required.
The location of the uitest.adoc and all autodocs it refers to.

.TP
.B IMOD_UITEST_DATA
Required.
The root directory of directories containing the stacks and other files to be copied to
the test dataset directory.  The directories that contain the stacks and other files
have the same name as the dataset.

.SS Global Attributes

.TP
.B sleep = \fIsleep_length
The number of milliseconds to sleep when the sleep attribute is used in the
\fBuitest-axis.adoc\fR.
The default is 1000 milliseconds.  One entry per file.
See Note 2 in the \fBuitestaxisadoc\fR man page.

.TP
.B Version = 1.2
Required.  The version of the autodoc format used.

.SS Test Section and Attributes

.TP
.B [Test = \fITest_section_name\fB]\fR
Required.  The Test section header.
Each Test section contains the information to test one instance of Etomo.

.TP
.B adoc\fR[\fB.\fR(\fBa\fR|\fBb\fR)]\fB = \fIuitest-axis_autodoc\fR
Required.
The name of an autodoc file used to test one axis of a dataset.
The autodoc will be found in the source directory (\fB$IMOD_UITEST_SOURCE\fR).
Use two entries and specify the axis when testing both the A and B axis.
Specify the B axis when testing only the B axis.
Uitest-axis autodocs can have any name, but they must have the extension .adoc.
Only one dataset may be tested per section.
Uitest-axis autodocs can be reused for different datasets.
Also sets the "axis" variable for the specified axis.
See \fBman uitestaxisadoc\fR.

.TP
.B copy.file = \fIfile_name
A dataset file to be copied into the dataset directory.
The file will be copied from the \fBdatadir\fR directory,
which should be set first.
\fIFile_name\fR should not contain expandable characters such as "*".
Use this attribute to copy any file
which can be copied before Etomo starts running.
If the \fBkeep\fR attribute is used with \fBdatasetdir\fR, then
\fIfile_name\fR will only be copied if it
doesn't exist in the dataset directory.

.TP
.B datadir = \fIrelative_directory_path\fR
Required.
The path of a directory which may containdataset files to be copied, and/or
files for comparison (see \fBcopy\fR).  The absolute directory path will be
$IMOD_UITEST_DATA/\fIrelative_directory_path\fR.
The section-level setting is used in the axis-level tests.

.TP
.B datafile = \fIdata_file_name
Causes the test program to run etomo with an .edf file.
Automatically overrides \fBdataset\fR, \fBfiducial-diameter\fR, and the SetupRecon
Dialog section (see the axis level ui test autodoc).

.TP
.B dataset = \fIdataset_name
The dataset that Etomo will create.
\fIDataset_name\fR will be automatically added to the Setup dialog.
One entry per Test section.
Also sets the "dataset" variable.
The \fBdataset\fR entry should appear before \fBcopy\fR entries.
.nf
Default:  Test_section_name.
.fi

.TP
.B datasetdir\fR[\fB.keep\fR]\fB = \fR[\fIrelative_directory_path\fR]
The directory path relative to the test directory which
will contain the test dataset for the current test.
This option is unnecessary if the dataset directory name is the same as the section name and
you want to remove all the files in the dataset directory before running the test.
Use the \fBkeep\fR option is used to prevent the test directory for
this section from being deleted and recreated each time the test is run.
The absolute directory path will be /\fIthe_run_directory\fR/UITests/\fIrelative_directory_path\fR.
One entry per Test section.  See \fB[Test = \fITest_section_name\fB]\fR.
If \fBdatasetdir\fR is used, it must appear before the \fBcopy\fR commands or
the default will be used.
.nf
Default absolute path:  /\fIthe_run_directory\fR/UITests/Test_section_name.
.fi

.TP
.B duration = \fR[\fIdays\fR]\fB:\fR[\fIhours\fR]\fB:\fR[\fIminutes\fR]\fR[\fB:\fIseconds\fR]
Duration causes the test program to end after the interval specified,
if it has not already completed.
If the test program ends this way,
it reports a failure.
This attribute ensures the completion of a test program which is waiting for a dialog,
process, or popup. 
.nf
Default duration:  15 minutes (\fB::\fI15\fR).
.fi 

.TP
.B set\fR[\fB.\fR(\fBa\fR|\fBb\fR)]\fB.\fIvariable_name\fB = \fR[\fIvalue\fR]
Creates a variable called \fIvariable_name\fR and assigns it a value.
These variables can be used in the value of an axis test section-level name/value pair.
If \fIvalue\fR is not used, the variable will be replaced with an empty string.
Axis-level variables can be set by using \fBa\fR or \fBb\fR.
Variables persist until the test is over.
They can be used as values in uitest axis autodoc section-level attributes.
Variables are refered to with the syntax \fB%{\fIvariable_name\fB}\fR.
Do not use the variables names "dataset" or "axis"
because they are set automatically.  Do not use the variable names "a" or "b".
Variable names may not contain ".", "/", "\", or the delimiter (default - "=").

.SH AUTHOR
Written by Sue Held.

.SH COPYRIGHT
Copyright @ 2005 Boulder Laboratory for 3-Dimensional Electron Microscopy of
Cells (BL3DEM), University of Colorado.

.SH SEE ALSO
.B uitestaxisadoc\fR(1), \fBpip\fR(1) \- Option Specifications in an Autodoc File.
