#!/bin/sh
#
# Description: startup script for eTomo
# 
# Copyright: Copyright (c) 2002, 2003
# Boulder Laboratory for 3D Fine Structure, University of Colorado
# 
# $Author$
# 
# $Revision$
# 
# $Log$
# Revision 1.5  2003/04/25 22:04:07  rickg
# Added echoing at startup
#

#  Workaround for java 1.4.0 / new threading library clash
export LD_ASSUME_KERNEL=2.4.1

# Test for existance of IMOD_DIR
if [ -z "$IMOD_DIR" ]; then
  echo "The IMOD_DIR environement variable has not been set"
  echo "Set it to point to the directory where IMOD is installed"
  exit
fi
if [ ! -e $IMOD_DIR ]; then
  echo "IMOD_DIR="${IMOD_DIR} " does not exist"
  echo "Set it to point to the directory where IMOD is installed"
  exit
fi

# Use the JRE distribute with Etomo for now
ETOMO_JAVAVM=$IMOD_DIR/jre/bin

# Copy the previous log files to backups
if [ -e etomo_out.log ]; then
  cp etomo_out.log etomo_out.log~
fi
if [ -e etomo_err.log ]; then
  cp etomo_err.log etomo_err.log~
fi
echo "starting eTomo"
$ETOMO_JAVAVM/java -cp $IMOD_DIR/bin/etomo -jar $IMOD_DIR/bin/etomo.jar $@ \
  2>etomo_err.log >etomo_out.log &
