#!/bin/sh
#
# Description: startup script for eTomo
# 
# Copyright: Copyright (c) 2002, 2003
# Boulder Laboratory for 3D Fine Structure, University of Colorado
# 
# $Author$
# 
# $Revision$
# 

# If you wish to use a different java runtime than the default uncomment the
# following line and define the path to the desired runtime direcotory

#export IMOD_JAVADIR=/usr/local/j2re1.4.0_04

if [ ! -z "$IMOD_JAVADIR" ]; then
  export PATH=${IMOD_JAVADIR}/bin:${PATH}
fi

# Test for appropriate java run time
if ! which java 2>&1 > /dev/null ; then
  echo "There is no java runtime in the current search path.  A Java runtime"
  echo "environment needs to be installed and the command search path needs"
  echo "to be defined to locate the java command."
fi

#  Workaround for java 1.4.0 / new threading library clash
export LD_ASSUME_KERNEL=2.4.1

# Test for existance of IMOD_DIR
if [ -z "$IMOD_DIR" ]; then
  echo "The IMOD_DIR environment variable has not been set"
  echo "Set it to point to the directory where IMOD is installed"
  exit
fi
if [ ! -e $IMOD_DIR ]; then
  echo "IMOD_DIR="${IMOD_DIR} " does not exist"
  echo "Set it to point to the directory where IMOD is installed"
  exit
fi


# If the system-dependent script for setting the library search path exists,
# source it.  This takes care of putting our Qt libraries on the right path
# variable, and allows other directories to be placed on the path too, to
# prevent clashes with libraries supplied by other packages

if [ -e ${IMOD_DIR}/bin/setlibpath ]; then
  . ${IMOD_DIR}/bin/setlibpath
fi

# Copy the previous log files to backups
if [ -e etomo_out.log ]; then
  cp etomo_out.log etomo_out.log~
fi
if [ -e etomo_err.log ]; then
  cp etomo_err.log etomo_err.log~
fi
echo "starting eTomo"
java -cp ${IMOD_DIR}/bin/etomo -jar ${IMOD_DIR}/bin/etomo.jar $@ \
  2>etomo_err.log >etomo_out.log &


# $Log$
# Revision 1.9  2003/09/03 20:04:50  mast
# There is no source command in sh - needed  . instead
#
# Revision 1.8  2003/09/03 17:40:01  mast
# Modified to use system-dependent 'setlibpath' to fix library paths
#
# Revision 1.7  2003/07/22 22:13:32  rickg
# Use JVM defined by the PATH
# Check to see if we have our our QTLIB
# Force the system QTLIB to the front of LD_LIBRARY_PATH if
# it exists.
#
# Revision 1.6  2003/06/13 19:24:29  rickg
# Added LD_ASSUME_KERNEL=2.4.1 export
#
# Revision 1.5  2003/04/25 22:04:07  rickg
# Added echoing at startup
#
  