#!/bin/sh

# Test for appropriate java run time
if ! type java > /dev/null ; then
  echo "There is no java runtime in the current search path.  Add the path to"
  echo "a java runtime (1.4 or greater) to your current command search path."
fi

# Test for existance of IMOD_DIR
if [ -z "$IMOD_DIR" ]; then
  echo "The IMOD_DIR environement variable has not been set"
  echo "Set it to point to the directory where IMOD is installed"
fi
if [ ! -e $IMOD_DIR ]; then
  echo "IMOD_DIR="${IMOD_DIR} " does not exist"
  echo "Set it to point to the directory where IMOD is installed"
fi

# Test for existence of etomo jar file

# Copy the previous log files to backups
if [ -e etomo_out.log ]; then
  cp etomo_out.log etomo_out.log~
fi
if [ -e etomo_err.log ]; then
  cp etomo_err.log etomo_err.log~
fi

java -cp $IMOD_DIR/bin/etomo -jar $IMOD_DIR/bin/etomo.jar \
  2>etomo_err.log >etomo_out.log &
