include ../configure

# Maintain the base name of the qt library here for installqtlib as
# the second name: the -lqt is just a tag for the sed operation to work
#
LIBS = -lqt qt-mt

all :

install	:
	$(CP) $(VCEXEDIR)/imodsendevent.exe $(INSTBINDIR)

clean :
