#!/bin/csh
#############################################################################
# $Id$
# Set up initialization file for building BL3DEMC Software.
# See setup2 for the real action
#
#  $Author$
#
#  $Date$
#
#  $Revision$
#  $Log$
#

#
# Just get the system name for cygwin test
#
set USYSTEM  = `uname -s`
#
# Convert the real setup file under cygwin and source it
#
switch ($USYSTEM)
    case CYGWIN*:
        dos2unix setup2 >& /dev/null
        breaksw
    default:
        breaksw
endsw

source setup2
