#!/usr/bin/env python
# 3dmodv - runs 3dmod in the background with -view argument
#
# Author: David Mastronarde
#
# $Id$

progname = '3dmodv'
prefix = 'ERROR: ' + progname + ' - '

# load System Libraries
import sys, os

#
# Setup runtime environment
if os.getenv('IMOD_DIR') != None:
   sys.path.insert(0, os.path.join(os.environ['IMOD_DIR'], 'pylib'))
   from imodpy import *
   addIMODbinIgnoreSIGHUP()
else:
   sys.stdout.write(prefix + " IMOD_DIR is not defined!\n")
   sys.exit(1)

bkgdProcess(['3dmod', '-view'] + sys.argv[1:])
sys.exit(0)
