#!/usr/bin/env python
# subm - runs submfg in the background for non-Cygwin Windows or if there is no alias
#
# Author: David Mastronarde
#
# $Id$

progname = 'subm'
prefix = 'ERROR: ' + progname + ' - '

# load System Libraries
import sys, os

#
# Setup runtime environment
if os.getenv('IMOD_DIR') != None:
   sys.path.insert(0, os.path.join(os.environ['IMOD_DIR'], 'pylib'))
   from imodpy import *
   addIMODbinIgnoreSIGHUP()
else:
   sys.stdout.write(prefix + " IMOD_DIR is not defined!\n")
   sys.exit(1)

#
# load IMOD Libraries
from pip import exitError, setExitPrefix
setExitPrefix(prefix)
args = ['submfg']
if 'win32' in sys.platform:
   args = ['submfg.cmd']

if len(sys.argv) > 1:
   args += sys.argv[1:]

bkgdProcess(args, None, 'stdout')
sys.exit(0)
