#!/usr/bin/env python
# subm - runs submfg in the background for non-Cygwin Windows or if there is no alias
#
# Author: David Mastronarde
#
# $Id$

progname = 'subm'
prefix = 'ERROR: ' + progname + ' - '

# load System Libraries
import sys, os, signal

#
# Setup runtime environment
if sys.platform.find("win32") < 0:
   try:
      signal.signal(signal.SIGHUP, signal.SIG_IGN)
   except Exception:
      pass
if os.getenv('IMOD_DIR') != None:
   os.environ['PATH'] = os.path.join(os.environ['IMOD_DIR'], 'bin') + \
                        os.pathsep + os.environ['PATH']
   sys.path.insert(0, os.path.join(os.environ['IMOD_DIR'], 'pylib'))
else:
   sys.stdout.write(prefix + " IMOD_DIR is not defined!\n")
   sys.exit(1)

#
# load IMOD Libraries
from imodpy import *
from pip import exitError, setExitPrefix
setExitPrefix(prefix)
args = ['submfg']
if 'windows' in sys.platform:
   args = ['submfg.cmd']

if len(sys.argv) > 1:
   args += sys.argv[1:]

bkgdProcess(args, None, 'stdout')
sys.exit(0)
