include ../../configure

# Make doc files and place them in upper directory
all :
# For testing
#	../../sourcedoc/$(SOURCEDOC_EXE) testin.html testout.html
#	../../sourcedoc/$(SOURCEDOC_EXE) -f testfin.html testfout.html

# Remove output files from upper directory
clean :
