char *Imod_hotkey_help[] = {
"3dmod Help for Hot Keys\n",
"----------------------\n",
"The following hot keys are available in the Zap, XYZ and Slicer Windows.\n",
"\n",
"Key     Function\n",
"------------------------------------------------------------------\n",
"        Model edit functions\n",
"        ----------------------------------------------------------\n",
"o\tGo to previous object.\n",
"p\tGo to next object.\n",
"[ \tGo to previous point.\n",
"] \tGo to next point.\n",
"C \tGo to next contour.\n",
"c \tGo to previous contour.\n",
"5/6\tGo to previous/next contour in same surface.\n",
"7/8\tGo to previous/next surface.\n",
"e \tUnselect current point.\n",
"E \tUnselect current contour.\n",
"{ \tGo to first point in contour.\n",
"} \tGo to last point in contour.\n",
"n \tCreate a new contour.\n",
"N\tCreate a new contour with a new surface number.\n",
"0\tCreate a new object.\n",
"Delete\tDelete current model point.\n",
"D\tDelete current contour.\n",
CTRL_STRING"-D\tTruncate current contour at current point.\n",
"M\tMove contour to selected object or surface.\n",
"J\tJoin selected contours.\n",
"m \tToggle model edit mode and movie mode.\n",
CTRL_STRING"-Z\tUndo changes to the model.\n",
CTRL_STRING"-Y\tRedo model changes that were undone.\n",
"\n",
"t \tToggle model drawing on/off.\n",
"T\tToggle point cursor on/off.\n",
"g \tToggle previous contour ghost draw mode.\n",
"\n",
"s \tSave model file.\n",
"S\tMake non-TIFF snapshot of image in window (Zap, XYZ, Slicer).\n",
CTRL_STRING"-S\tMake TIFF snapshot of image in window (Zap, XYZ, Slicer).\n",
"f \tPrint current pixel value in information window.\n",
"F \tFind the maximum pixel within 10 pixels and report its value.\n",
",\tDecrease movie speed.\n",
".\tIncrease movie speed.\n",
"-\tDecrease Zoom\n",
"=\tIncrease Zoom\n",
"3/4\tStart or stop a movie through time in forward/reverse direction.\n"
"\n",
"        Position control, move current viewing point.\n",
"        -----------------------------------------------------------\n",
"Page Up     \tIncrease Z\n",
"Page Down   \tDecrease Z\n",
"Up Arrow    \tIncrease Y\n",
"Down Arrow \tDecrease Y\n",
"Right Arrow\tIncrease X\n",
"Left Arrow\tDecrease X\n",
"End\t\tGo to Z = 1;\n",
"Home\t\tGo to Z = max;\n",
"Insert\t\tGo to middle Z of stack\n",
"1,2\t\tPrevious,Next Time Index.\n",
"\n",
"Keypad Arrows\tMove current model point in model mode,\n",
"\t\tPan in zap window in movie mode. \n",
"Arrows\t\tPan in zap window in model mode.\n",
"\n",
"\n",
"        Contrast functions.\n",
"        -----------------------------------------\n",
"A \tAutocontrast - set to target mean and SD of intensity.\n",
"F1 \tDecrease Black Level\n",
"F2 \tIncrease Black Level\n",
"F3\tDecrease White Level\n",
"F4 \tIncrease White Level\n",
"\n",
"F5 \tDecrease Contrast.\n",
"F6 \tIncrease Contrast.\n",
"F7 \tDecrease Brightness.\n",
"F8 \tIncrease Brightness.\n",
"\n",
"F9  \tSelect Color map ramp # 1.\n",
"F10\tCycle through Color map ramps: 1 - 2 - 3 - 4 - 1.\n",
"F11 \tInvert Color map.\n",
"F12 \tToggle False Color.\n",
"\n",
"        Window control.\n",
"        -----------------------------------------\n",
"\\ \tOpen Slicer Window.\n",
"v\tOpen Model View Window.\n",
"G\tOpen Graph window.\n",
"z\tOpen Zap window.\n",
CTRL_STRING"-R\tRaise all 3dmod windows above other windows.\n"
"\n",
"\n",
"",
 NULL};
