char *Imod_help_text[] = {
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"NAME\n",
"       imod - Make a model from a 3-D image stack.\n",
"\n",
"SYNOPSIS\n",
"       imod [options] [image filenames]  [model filename]\n",
"\n",
"DESCRIPTION\n",
"       Imod is typically invoked with one image file, but\n",
"       multiple image filenames can also be given.  The model\n",
"       filename is optional; if imod is called without a model\n",
"       file it will create a new model.  The user can load new\n",
"       model files using a menu selection once imod is running.\n",
"       If the model file does not already exist, imod will create\n",
"       a new model under that name.  The image files may also be\n",
"       omitted, in which case imod will draw the model on top of\n",
"       blank images.  A file containing a list of image files can\n",
"       be used in place of the image file names on the command\n",
"       line.  If multiple files of different sizes are loaded,\n",
"       then the size of the display in each dimension will be\n",
"       limited to the minimum size of the various files.  If imod\n",
"       is invoked with options but no filenames, then a dialog\n",
"       window will open to allow selection of an image file.\n",
"\n",
"\n",
"       The model must be in the IMOD model format.  Images must\n",
"       be in the MRC image format, or in the TIFF format, if the\n",
"       appropriate TIFF library is available.  MRC files of\n",
"       almost any mode can be read in: byte, 16-bit integer,\n",
"       real, complex real, complex integer, or color (RGB).  TIFF\n",
"       files may be byte, 16-bit integer, or color; they may be\n",
"       organized in strips but not in tiles.  TIFF files with\n",
"       various kinds of compression can be read, depending on the\n",
"       capabilities of the libraries on the system.  When\n",
"       multiple files are read in, they do not need to be the\n",
"       same mode or even the same format (except that if any file\n",
"       is an RGB file, all files must be.)  Whenever a TIFF file,\n",
"       an RGB-mode file, or more than one file is specified,\n",
"       images are loaded only as they are needed into an image\n",
"       cache.  This has various implications that are mentioned\n",
"       below.  Starting a movie through the images will\n",
"       eventually load all of the data into the cache, at which\n",
"       point the program will perform very similarly to the way\n",
"       it does without the cache.  Several other restrictions\n",
"       exist.  If any TIFF or RGB-mode files are loaded, the\n",
"       image volume cannot be flipped (Y and Z exchanged).  The\n",
"       Pixel View window, high-resolution mode in the Graph\n",
"       window, and the f and F hotkeys for finding pixel values\n",
"       will all give zeros for a TIFF file.  If RGB files are\n",
"       loaded, only the Zap and Model View windows can be opened.\n",
"\n",
"\n",
"       Two windows will open upon startup: the Information Window\n",
"       and an image window.  The Information Window is the main\n",
"       control window; it has a menu bar and has indicators that\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             1\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"       give information about the selected model point and the\n",
"       selected graphics voxel.  The bottom of the information\n",
"       window also has a status box that shows the progress of\n",
"       certain operations while using imod.  While the image is\n",
"       loading, the Information Window will report the status of\n",
"       the image load.  Selecting the Quit menu item from the\n",
"       File menu will cancel the image load.  If the image cache\n",
"       feature is used, the image window will open up after the\n",
"       first image section is loaded; otherwise, the image window\n",
"       won't open until the entire image has been loaded.\n",
"\n",
"       The ZaP Window is the default image display window used by\n",
"       imod.  It allows one to view an image at any magnification\n",
"       and to pan the image around inside a resizable window.\n",
"       Most manual model editing is done within the ZaP Window.\n",
"\n",
"\n",
"       Additional windows that may be opened via menu selection\n",
"       are the Slicer, XYZ, Tumbler, Tilt, Graph, Pixel View, and\n",
"       Model View windows.\n",
"          The Slicer Window allows one to view slices through the\n",
"       3-D image data.  If the image cache is turned on, only\n",
"       images in the cache will be displayed in views that\n",
"       contain data from multiple Z sections.\n",
"          The XYZ Image Window displays slices of the 3-D image\n",
"       in planes perpendicular to the X,Y and Z axis.\n",
"          The Tumbler Window allows one to view a small projected\n",
"       view of the area around the current point.\n",
"          The Tilt Window allows one to load a tilt image file\n",
"       and have it linked to the XYZ Image Window.\n",
"          The Graph Window graphs intensity along a given axis or\n",
"       along a given contour.\n",
"          The Pixel View Window shows the actual pixel values\n",
"       from the image file around a given point.\n",
"          The Model View Window views the model in a 3D rendering\n",
"       while it's being built.\n",
"\n",
"\n",
"\n",
"   Options\n",
"       imod will accept the standard Xt toolkit options along\n",
"       with the following options:\n",
"\n",
"       -x <min,max>\n",
"       -y <min,max>\n",
"       -z <min[,max]>\n",
"              The -x, -y and -z options can be used to load in a\n",
"              sub-area of the original image.  The offsets are\n",
"              saved in the model so if a different area is loaded\n",
"              the model is automatically transformed to match the\n",
"              new sub area.\n",
"\n",
"       -m     This option overrides the model transformation\n",
"              behavior and causes the model to be loaded without\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             2\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"              any transformations.  The default model position\n",
"              data will be loaded.\n",
"\n",
"       -xyz   This option causes the default image window to be\n",
"              the XYZ window instead of the ZaP window.  There\n",
"              was a time when the XYZ window was actually more\n",
"              useful than the ZaP window.\n",
"\n",
"       -Y     This option causes the image data to be flipped\n",
"              after it has been loaded.  This allows one to model\n",
"              image planes that are normal to the Y-axis.  The\n",
"              default is to model planes normal to the Z-axis.\n",
"              It is possible to flip back and forth between these\n",
"              two modeling orientations using the Edit Image menu\n",
"              item Flip.\n",
"\n",
"       -h -help\n",
"              Print some quick help for imod's command line\n",
"              options to the terminal.\n",
"\n",
"       -C <value>\n",
"              The -C option controls the image cache used by\n",
"              imod.  The default value is 0 which means imod will\n",
"              try to load the entire image into memory.  This\n",
"              option can force a given number of images to be\n",
"              cached.  Alternatively, one can limit the size of\n",
"              the cache in megabytes by entering a value with m\n",
"              or M on the end.  For example, -C 200M will limit\n",
"              the cache to 200 megabytes.  The reason for using\n",
"              this option is either to decrease start up time or\n",
"              to view large data sets that can't fit into main\n",
"              memory.  This features works best with the ZaP\n",
"              Window, which always loads the image that it needs\n",
"              into the cache.  Other image windows will only be\n",
"              able to access image data that are already within\n",
"              the cache.\n",
"\n",
"       -p <filename>\n",
"              Load a file containing a piece list for the input\n",
"              image.  This allows one to montage image sections\n",
"              together or to view images that are either missing\n",
"              sections or have sections out of order.  The piece\n",
"              list is an ASCII text file with the following\n",
"              format.  There are as many lines as the input image\n",
"              has frames (the z dimension of the image file).\n",
"              Each line contains three values <X> <Y> and <Z>\n",
"              which represent the starting location of each frame\n",
"              in the input image stack.  Using the piece list\n",
"              option will also turn on the image cache with a\n",
"              default size equal to the total number of image z-\n",
"              planes that contain data.  The image cache can't be\n",
"              turned off, but the size can be changed with the -C\n",
"              option.\n",
"\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             3\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"       -P <nx,ny>\n",
"              Create an internal piece list to display images\n",
"              from the file in a montage of nx by ny pieces.  If\n",
"              an external piece list file is entered with the -p\n",
"              option, then this option is ignored; with this\n",
"              option, montage information in the file header is\n",
"              ignored.\n",
"\n",
"       -o <nx,ny>\n",
"              When creating an internal piece list with the -p\n",
"              option, set the overlap between pieces to nx in the\n",
"              X direction and ny in the Y direction.  Enter\n",
"              negative numbers to get space (gutters) between the\n",
"              pieces.\n",
"\n",
"       -f     Load file as individual frames, overriding montage\n",
"              information in the image file header.  It is\n",
"              possible for an image file to have piece\n",
"              coordinates stored in its header rather than in a\n",
"              separate piece list file.  Imod will automatically\n",
"              load such a file as a montage, so this option is\n",
"              available to override this behavior and force\n",
"              loading as individual frames.\n",
"\n",
"\n",
"       -c <value>\n",
"              The -c option selects a starting color table used\n",
"              for displaying image data.  This allows additional\n",
"              copies of imod to run and display images with\n",
"              different contrasts.  The default value is 1 and\n",
"              the allowed range is 1-12.  This option is ignored\n",
"              on 8-bit and RGB graphics displays.  On SGI\n",
"              machines, imod attempts to determine the number of\n",
"              other imods are already running and selects a color\n",
"              table value one higher than this number.  The color\n",
"              table can be changed from within imod using the\n",
"              Edit Image menu item Colormap.\n",
"\n",
"       -rgb   Display images in 24-bit color mode rather than\n",
"              using a color table.  This option is needed on an\n",
"              SGI when trying to display color images, i.e. MRC\n",
"              files in RGB-mode or TIFF files containing RGB\n",
"              images.\n",
"\n",
"       -G     Display an RGB-mode MRC file in gray-scale rather\n",
"              than in color.  If there are multiple MRC files, if\n",
"              the file is specified by an image list, or if the\n",
"              file on the command line is a color TIFF file, it\n",
"              will be displayed in color regardless of this\n",
"              option.\n",
"\n",
"       -s <min,max>\n",
"              The -s option will scale image intensities linearly\n",
"              so that the min and max values will be displayed as\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             4\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"              black (0) and white (255) on the screen.  Without\n",
"              this option, intensities are scaled between the\n",
"              minimum and maximum intensities in the image file.\n",
"              Images can be rescaled after imod is running using\n",
"              the Edit Image menu item Reload.\n",
"\n",
"\n",
"Information Window\n",
"       The Information Window is imod's main control window and\n",
"       it is open at all times while imod is running.  All other\n",
"       windows can be opened and closed without restarting imod.\n",
"\n",
"\n",
"       The Model Selection Display Gadgets.\n",
"              The current Object, Contour and Point are displayed\n",
"              and can be changed using the arrow buttons.  Models\n",
"              are a collection of objects, and each object has\n",
"              its own display color, drawing style and list of\n",
"              contours.  Each contour in turn contains a list of\n",
"              points.  When drawing the current contour the\n",
"              beginning point is green, the end point is red and\n",
"              the current point is yellow.  One can also move\n",
"              between the current Object, Contour and Point using\n",
"              hot keys in selected image windows.\n",
"              p/o - Go to the next/previous Object.\n",
"              C/c - Go to the next/previous Contour.\n",
"              ]/[ - Go to the next/previous Point.\n",
"\n",
"       The Image Position Display Gadgets.\n",
"              The current image size and position is displayed\n",
"              and can be edited using the arrow buttons.  The\n",
"              arrow keys on the keyboard can also be used to move\n",
"              the current image point. The current Z coordinate\n",
"              can be moved with the Page Up and Page Down keys.\n",
"\n",
"       Image level Sliders.\n",
"              The Black and White sliders can be used to adjust\n",
"              the contrast and brightness of the input image for\n",
"              all the image windows.  A linear intensity ramp is\n",
"              made from the black level to the white level.  The\n",
"              Function keys also can be used to control the image\n",
"              level from other image windows.\n",
"              F1, F2  Controls the Black slider level.\n",
"              F3, F4  Controls the White slider level.\n",
"              F5, F6  Controls the image contrast by moving the\n",
"                        Black and White sliders either apart or closer.\n",
"              F7, F8  Controls the image brightness by moving the\n",
"                        Black and White sliders in tandem.\n",
"              F9      Select Color map ramp # 1.\n",
"              F10     Cycle through Color map ramps, 1 - 2 - 3 - 4 - 1.\n",
"              F11     Toggle the reversed colormap.\n",
"              F12     Toggle False Color.\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             5\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"       The Float Checkbox.\n",
"              When this box is checked, imod will attempt to\n",
"              maintain comparable image contrast when going from\n",
"              one section to the next.  It automatically adjusts\n",
"              the sliders when you change sections in a ZaP\n",
"              window, based on the mean and standard deviation of\n",
"              image intensity in the sections.\n",
"\n",
"       The Mode Toggle Buttons.\n",
"              One can toggle between Movie mode and Model mode.\n",
"              The model can't be edited while in movie mode.\n",
"              When imod first opens a new model it switches to\n",
"              movie mode.\n",
"\n",
"\n",
"       The Menu bar\n",
"              Menus for imod are selected by holding down the\n",
"              left mouse button while inside the information\n",
"              window.  Some menus have keyboard shortcuts (shown\n",
"              in parentheses).  Menu entries with ... open a\n",
"              dialog box, control window, or display window.\n",
"\n",
"              File Menu\n",
"              New Model         Create a new model.\n",
"              Open Model...     Load a model from disk.\n",
"              Save Model        Save model.  (s)\n",
"              Save Model as...  Save model with new name.\n",
"              Write Model as    Write model as Imod, wimp, NFF or Synu files.\n",
"              Memory to TIFF... Write the whole section of a raw color image\n",
"                                  stored inside imod to a TIFF file, in order to\n",
"                                  turn a montaged image bigger than the screen\n",
"                                  into a single large image.\n",
"              About             Info about imod.\n",
"              Quit              Quit imod.\n",
"\n",
"              Edit Menu\n",
"              Model\n",
"                 Header...   Set the model's Z-Scale for viewing, its pixel\n",
"                                size, resolution (spacing between points during\n",
"                                contour drawing), and whether the model is drawn\n",
"                                or not.\n",
"                 Offsets...  Offset the model data in X, Y and Z.\n",
"                 Clean       Delete all objects that contain no points (i.e.,\n",
"                                that have no contours, or only contours with no\n",
"                                points).\n",
"\n",
"              Object\n",
"                 New       Create a new object.  Opens Object Type dialog box.\n",
"                 Delete    Delete current object.\n",
"                 Color...  Open requester for changing object color.\n",
"                 Type...   Edit Object type.\n",
"                 Go To...  Select the current object with a slider.\n",
"                 Move...   Move all contours from current object to another\n",
"                              object.\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             6\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"                 Info      Calculate volume and surface area of current object.\n",
"                 Clean     Delete empty contours in the current object.\n",
"\n",
"              Surface\n",
"                 New       Create a new contour with a new surface number.  (N)\n",
"                 Go To...  Select a different surface with a slider in the\n",
"                              Contour Type window.\n",
"                 Move...   Move contours in a surface to a different object or\n",
"                              a different surface using the Contour Move window.\n",
"\n",
"              Contour\n",
"                 New       Create a new contour.  (n)\n",
"                 Delete    Deletes the current contour.  (D)\n",
"                 Move...   Move current contour to a different object or\n",
"                             surface.\n",
"                 Sort      Sort contours by Z value and by time value.\n",
"                 Auto...   Make new contours using threshold.\n",
"                 Type...   Edit contour internal data, such as\n",
"                              surface #, time index and labels.\n",
"                 Go To...  Select the current contour with a slider.\n",
"                 Info      Print area and/or length of contour.\n",
"                 Break...  Break contour into two contours.  Closed contours can\n",
"                              have two break points.\n",
"                 Fix by Z  Break a closed contour at every change in Z, creating\n",
"                              as many contours as necessary so that each lies in\n",
"                              a single Z plane.\n",
"                 Join...   Join two contours together.  Closed contours will be\n",
"                              joined at the nearest point; open contours will be\n",
"                              joined such that the joined contour will have\n",
"                              points up to the first selected point from the\n",
"                              first contour and from the second selected point\n",
"                              to the last point from the second contour.\n",
"                 Invert    Invert the order of points in the current contour.\n",
"                 Copy...   Copy contours to a different object, Z-level, or\n",
"                              time.\n",
"                 Loopback  Add points to the end of a contour so that it loops\n",
"                              back from its current end to its start along the\n",
"                              same path.  Such a contour can be used to make a\n",
"                              complex cap over an elongated, oddly shaped\n",
"                              contour.\n",
"                 Fill In   For an open contour that traverses through Z, add\n",
"                              points by interpolation to fill in any gaps where\n",
"                              the contour skips one or more sections.\n",
"\n",
"              Point\n",
"                 Delete        Delete Current point.  (Delete)\n",
"                 Sort by dist  Sort points in a contour by interpoint distance.\n",
"                 Sort by Z     Sort points in a contour by Z value.\n",
"                 Distance      Show distance between current and last model\n",
"                                  points.\n",
"                 Value         Show current voxel value from image file.\n",
"                 Go To...      Select the current point with a slider.\n",
"                 Size...       Set size of individual points.\n",
"\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             7\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"              Image\n",
"                 Process...    Process images by filtering.\n",
"                 Colormap...   Change color table number.\n",
"                 Reload...     Open the image scale reload requester.\n",
"                 Flip          Exchange Y and Z dimensions of the image data.\n",
"\n",
"              Movies...    Open window to control movie limits in X, Y, Z and\n",
"                               time.\n",
"\n",
"              Image Menu\n",
"                 Graph       Open an image Graph window.  (G)\n",
"                 Slicer      Open an image Slicer window.  (\\)\n",
"                 Tumbler     Open a 3-D Tumbler window.\n",
"                 Tilt...     Load Extra Tilt Image for viewing.\n",
"                 Model View  Open an imod model view window.  (v)\n",
"                 ZaP         Open the ZaP window.\n",
"                 XYZ         Open the XYZ window.\n",
"                 Pixel View  Open window displaying pixel values.\n",
"\n",
"              Special menu\n",
"              This menu provides access to plugins found by imod\n",
"              when it starts.  Plugins may include ones for\n",
"              working with data from 4D microscopes, the Bead\n",
"              Fixer to assist with correcting models of fiducial\n",
"              markers for aligning tilt series, and the Line\n",
"              Tracker, which performs semi-automated modeling of\n",
"              linear features such as membranes.\n",
"\n",
"              Help Menu\n",
"              This menu provides help for controls used in imod.\n",
"              Topics include Man Page, Menus, and Hot Keys.\n",
"\n",
"\n",
"ZaP Window\n",
"       The ZaP window allows one to zoom and pan inside of a\n",
"       model window that shows image sections perpendicular to\n",
"       the Z-axis.\n",
"\n",
"          To Zoom press the - and = Keys.  To pan, press the left\n",
"       mouse button and drag the mouse.  Alternatively, use the\n",
"       arrow keys: the ones on the numeric keypad in movie mode,\n",
"       or the set of 4 arrow keys in model mode.\n",
"\n",
"\n",
"          There is a toolbar at the top of the ZaP window that\n",
"       controls additional behavior.  Press the help button on\n",
"       the toolbar for help.  The space bar on the keyboard can\n",
"       toggle the toolbar visibility.\n",
"\n",
"          The mouse buttons are assigned different functions in\n",
"       movie and model modes.  The keyboard m key toggles between\n",
"       movie and model modes.  Other sub modes can further change\n",
"       the mouse controls.\n",
"\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             8\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"       Left mouse button\n",
"              One can drag the image in the ZaP Window by moving\n",
"              the mouse while holding down the left mouse button.\n",
"              If the rubber band is on and the button is held\n",
"              down while the pointer is near the band, one can\n",
"              drag a corner or edge of the band to adjust its\n",
"              size.  When the button is clicked in model mode,\n",
"              the nearest modeling point is selected.  If no\n",
"              points are in proximity to the cursor, then no\n",
"              point is selected.  The selected point's color is\n",
"              yellow.  In movie mode the current position is\n",
"              selected.\n",
"\n",
"       Middle mouse button\n",
"              In model mode, this creates a point after the\n",
"              current model point (or before, if the modeling\n",
"              direction is set with i or the toolbar button.)\n",
"              Holding down the middle mouse button will create\n",
"              additional points as the mouse moves.  In movie\n",
"              mode, this starts the movie through sections in the\n",
"              forward direction.  If the rubber band is on and\n",
"              the button is held down while the pointer is near\n",
"              the band, one can drag the whole band to a new\n",
"              position.\n",
"\n",
"       Right mouse button\n",
"              In model mode, the selected point is modified to be\n",
"              at the current location.  Holding down the right\n",
"              mouse button will cause additional points to be\n",
"              moved, until the end of the contour is reached.  If\n",
"              the Ctrl key is held down, then this mouse button\n",
"              can be used to delete points under the cursor.\n",
"              Clicking the button will delete the point(s) at the\n",
"              curretn mouse position; holding the button down and\n",
"              moving the mouse will delete all of the points that\n",
"              the cursor sweeps over.  In movie mode, the right\n",
"              mouse button starts the movie through sections in\n",
"              the reverse direction.\n",
"\n",
"\n",
"       Keyboard Controls\n",
"              Controls that edit models are disabled in movie\n",
"              mode.\n",
"\n",
"                      Modeling and display control keys\n",
"                      ---------------------------------\n",
"              o  -  Go to previous object\n",
"              p  -  Go to next object\n",
"              ]  -  Go to previous point\n",
"              [  -  Go to next point\n",
"              C  -  Go to next contour\n",
"              c  -  Go to previous contour\n",
"              5  -  Go to previous contour in current surface\n",
"              6  -  Go to next contour in current surface\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                             9\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"              7  -  Go to previous surface in current object\n",
"              8  -  Go to nextsurface in current object\n",
"              e  -  Unselect current point\n",
"              E  -  Unselect current contour\n",
"              {  -  Go to first point in contour\n",
"              }  -  Go to last point in contour\n",
"              n  -  Create a new contour\n",
"              N  -  Create a new contour with a new surface number\n",
"              0  -  Create a new object\n",
"              Delete - Delete current model point\n",
"              D  -  Delete current contour\n",
"              M  -  Move contour to selected object\n",
"              b  -  Build a contour while in auto contour mode\n",
"              m  -  Toggle model edit mode and movie mode\n",
"              t  -  Toggle model drawing on/off\n",
"              T  -  Toggle point cursor on/off\n",
"              g  -  Toggle previous contour ghost draw mode\n",
"              s  -  Save Model File\n",
"              f  -  Print current pixel value in information window\n",
"              F  -  Find the maximum pixel within 10 pixels and report its value\n",
"              ,  -  Decrease movie speed\n",
"              .  -  Increase movie speed\n",
"              -  -  Decrease Zoom\n",
"              =  -  Increase Zoom\n",
"              3  -  Start or stop a movie through time in the forward direction\n",
"              4  -  Start or stop a movie through time in the backward direction\n",
"\n",
"                      Other keys active in the ZaP window only\n",
"                      ----------------------------------------\n",
"              S  -  Snapshot image in window to RGB file\n",
"              Ctrl-S - Snapshot image in window to TIFF file\n",
"              i  -  Toggle the modeling direction\n",
"              Z  -  Toggle auto section advance on and off\n",
"              B  -  Toggle rubber band on and off\n",
"              I  -  Print information about window, image size, and offsets\n",
"              R  -  Resize window to size of image or rubber band\n",
"              Keypad Ins - Add point(s) in model mode, like middle mouse button\n",
"              Esc - Close ZaP window\n",
"\n",
"                      Keys to control position or move the current viewing point\n",
"                      -----------------------------------------------------------\n",
"              Page Up       -  Increase Z\n",
"              Page Down     -  Decrease Z\n",
"              Up Arrow      -  Increase Y\n",
"              Down Arrow    -  Decrease Y\n",
"              Right Arrow   -  Increase X\n",
"              Left Arrow    -  Decrease X\n",
"              End           -  Go to Z = 1\n",
"              Home          -  Go to Z = max\n",
"              Insert        -  Go to middle Z of stack\n",
"              h,l           -  Previous,Next Time Index\n",
"              j,k           -  Previous,Next Z Index\n",
"\n",
"              Keypad Arrows -  Move current model point in model mode,\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                            10\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"                            -  Pan in ZaP window in movie mode.\n",
"              Arrows        -  Pan in ZaP window in model mode\n",
"\n",
"                      Window control keys\n",
"                      -----------------------------------------\n",
"              \\  -  Open Slicer Window\n",
"              v  -  Open Model View Window\n",
"              G  -  Open Graph window\n",
"              z  -  Open ZaP window (from XYZ window)\n",
"\n",
"\n",
"Slicer Window\n",
"       Multiple Slicer Windows can be opened. Each Slicer Window\n",
"       shows a different slice through a 3-D volume.  Three\n",
"       sliders are used to select the orientation of the slice by\n",
"       setting the angles of rotation of the data volume around\n",
"       the X, Y and Z axes.  A small display next to the sliders\n",
"       gives a visual cue to the slice location.  One can model\n",
"       in the Slicer Window, using the middle mouse button to\n",
"       insert a point after the current point, or the right\n",
"       button to modify the current point.  The Tool bar on top\n",
"       of the Slicer has the following buttons, from left to\n",
"       right.\n",
"          The Up and Down arrows adjust the magnification in the\n",
"       slicer display window.\n",
"          The Show Slice button will draw where the slice\n",
"       intersects the X- Y- and Z-planes in the XYZ window, and\n",
"       the Z-plane in the ZaP window.\n",
"          The Lock button will keep the Slicer from changing its\n",
"       current position when locked.\n",
"          The checkerboard button toggles between nearest\n",
"       neighbor and slower, cubic interpolation.\n",
"          The option menu selects whether the angle sliders,\n",
"       depth controls, or just the Slicer image will be\n",
"       displayed.\n",
"          The Help button opens up on line help.\n",
"\n",
"       Hot Keys in the Slicer\n",
"              -/=  -  Decrease/Increase zoom\n",
"              _/+  -  Decrease/Increase displayed image thickness\n",
"              9/0  -  Decrease/Increase displayed model thickness\n",
"              s    -  Show slice in ZaP and XYZ windows\n",
"              S    -  Snapshot to RGB file\n",
"              Ctrl-S - Snapshot to TIFF file\n",
"              x/y/z  - Align current and last model points along X, Y or Z axis\n",
"              X/Y/Z  - Align first and last points of current contour along\n",
"                          X, Y or Z axis\n",
"\n",
"              Numeric Keypad:\n",
"              4/6  -  (Left/Right) Decrease/Increase last adjusted angle by 0.1\n",
"              2/8  -  (Down/Up) Decrease/Increase last adjusted angle by 0.5\n",
"              0    -  (Insert) Set last adjusted angle to 0\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                            11\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"Tumbler Window\n",
"       The Tumbler Window is opened by selecting the Tumbler item\n",
"       from the Image menu.  The area around the current point\n",
"       will be shown in the Tumbler Window.\n",
"       The arrow keys tumble the image.\n",
"       The -/= keys zoom the image.\n",
"       The F1,F2,F3,F4 keys adjust the contrast.\n",
"       The 'b' key toggles on/off the bounding box.\n",
"\n",
"Tilt Window\n",
"       The Tilt Window is opened by selecting the Tilt menu item\n",
"       from the Image menu.  Once the Tilt Window is selected a\n",
"       file requester appears.  One can enter an mrc file name or\n",
"       enter an ascii file name with the following format.\n",
"            tilt First line is mrc image file name.\n",
"            0    Lines 2-4 are translation values for x,y,z\n",
"            0\n",
"            0\n",
"            1    Lines 5-7 are scale values for x,y,z.\n",
"            1\n",
"            1\n",
"            0    Lines 8-10 are angles x,y,z.\n",
"            0\n",
"            0\n",
"            -10  Lines 11-end are a list of tilts.\n",
"            5\n",
"            0\n",
"            5\n",
"            10\n",
"       If a file name is given the tilt image is then loaded;\n",
"       otherwise the current image in imod is used.  The tilt\n",
"       window will draw the current contour.\n",
"\n",
"       Keyboard control hot keys for the tilt window image area.\n",
"              m    Toggle Movie on / off.\n",
"              -    Decrease Stereo Parallax.\n",
"              +    Increase Stereo Parallax.\n",
"\n",
"              Page Up     - Increase tilt angle view.\n",
"              Page Down   - Decrease tilt angle view.\n",
"\n",
"              Function Keys\n",
"              F1-F2 Adjust Black level.\n",
"              F3-F4 Adjust White level.\n",
"\n",
"Graph Window\n",
"       This window graphs image intensity along the image X-axis,\n",
"       Y-axis, Z-axis or along the current contour.  A histogram\n",
"       of image intensities can also be graphed.  The type of\n",
"       graph can be chosen by using the option menu located in\n",
"       the tool bar.  The [+] and [-] buttons in the tool bar\n",
"       adjust the zoom in the drawing area.  The [LOCK] button\n",
"       stops the window from tracking the current point.  The\n",
"       [RESOLUTION] button toggles between taking data from the\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                            12\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"       image buffer and taking data from the file.\n",
"\n",
"\n",
"Model View Window\n",
"       This window shows the model in 3D, continually updated as\n",
"       the model is edited.  The window behaves the same as when\n",
"       it is started with the imodv command.  See the manual page\n",
"       for imodv(1).\n",
"\n",
"\n",
"AUTOSAVE AND BACKUP FILES\n",
"       The program will back up the current model to the file\n",
"       model_file_name#autosave# every few minutes.  If no model\n",
"       file has been saved yet, the name of the autosave file is\n",
"       just #autosave#.  The autosave file is eliminated whenever\n",
"       the model is saved, and when the program exits normally.\n",
"       The IMOD_AUTOSAVE environment variable sets the number of\n",
"       seconds between automatic saves.  If it is set to 0 then\n",
"       this feature will be disabled.  The first time that you\n",
"       save a model file, the existing model file will be renamed\n",
"       to model_file_name~, and any existing file by that name\n",
"       will be deleted.  This backup file will not be overwritten\n",
"       each time that you save thereafter, so that it will\n",
"       preserve the state of the model when imod was started.\n",
"\n",
"       The IMOD_AUTOSAVE_DIR environment variable can be set to\n",
"       specify a directory in which the autosave file will be\n",
"       written.  Thus, one can specify a directory on a local\n",
"       disk (e.g., /usr/tmp) and avoid the long delays required\n",
"       to write a large model to a disk over the network.\n",
"\n",
"\n",
"SURFACES, OPEN CONTOURS, LABELS, AND POINT SIZES\n",
"       Several features can be controlled from the Contour Type\n",
"       window.  One is the surface, which is an optional level of\n",
"       organization between contours and objects.  With surfaces,\n",
"       one can keep track of, navigate between, and manipulate\n",
"       groups of contours without having to use a separate object\n",
"       for each group.  Each contour in an object has a surface\n",
"       number, which is 0 if surfaces are never employed.  To\n",
"       start a new surface, use N or the New Surf button in the\n",
"       Contour Type window to obtain a new, empty contour with\n",
"       the new surface number.  Thereafter, each new contour will\n",
"       have the same surface number as the previous contour being\n",
"       modeled, until a new surface is started again.  The\n",
"       Contour Type window has controls for moving within and\n",
"       between surfaces and for visualizing contours of the\n",
"       current surface.  The Contour Move window has options for\n",
"       moving contours from one surface to another or for moving\n",
"       an entire surface to a new object.\n",
"\n",
"       The Contour Type window has buttons for controlling two\n",
"       kinds of ghost displays.  The Surface Ghost button allows\n",
"       one to highlight contours of the current surface.  The\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                            13\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"       Section Ghost buttons control the display of ghost\n",
"       contours from adjacent sections, which is also toggled by\n",
"       the g hotkey.\n",
"\n",
"       The Contour Type window has a button for defining\n",
"       individual contours as open in an object defined as having\n",
"       closed contours.  This is useful for displaying a\n",
"       partially cut edge of an object.  See imodmesh(1) for more\n",
"       details.\n",
"\n",
"       This window also has a text box for displaying and editing\n",
"       the time index of the current contour.  If you have loaded\n",
"       multiple image files and want to model contours at\n",
"       specific times (i.e., displayed only on images from a\n",
"       specific file), you must first activate time editing with\n",
"       a button in the Edit-Object-Type window.  Once this\n",
"       feature is selected, newly created contours will be\n",
"       assigned to the currently displayed time.\n",
"\n",
"       The Contour Type window also has text boxes in which one\n",
"       can enter labels for individual contours and points.\n",
"       Finally, it has a text box and slider for assigning a size\n",
"       value to an individual point.  While this value can be\n",
"       anything, not just a size, it is interpreted as a size\n",
"       when the type of the object is scattered points rather\n",
"       than contours.\n",
"\n",
"\n",
"IMAGE LIST FILES\n",
"       An image list file can be entered instead of an image file\n",
"       on the imod command line.  This ASCII file can specify a\n",
"       series of image files that represent different times, so\n",
"       that one can step through time as well as X, Y, and Z.  An\n",
"       image list file can also be used to specify both an image\n",
"       file and a piece list with a single file.  In either case,\n",
"       the cache is turned on.  Lines beginning with # are\n",
"       treated as comments and ignored.\n",
"\n",
"       The format of the file is:\n",
"\n",
"       IMOD image list               [must be the first line of the file]\n",
"       VERSION 0   or   VERSION 1    [must appear somewhere in file]\n",
"\n",
"       To specify a series of files at different times, include a\n",
"       series of entries of the form (the second entries for time\n",
"       labels are optional, and default label if it is omitted is\n",
"       the image filename):\n",
"\n",
"       IMAGE image_filename\n",
"       TIME time_label               [The label can be any desired text]\n",
"\n",
"       If the first file might not exist, precede the list of\n",
"       images with a line:\n",
"       SIZE nx,ny,nz                 [nx,ny,nz are the image dimensions\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                            14\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"imod(1)                                                   imod(1)\n",
"\n",
"\n",
"                                      to be assumed for the first file]\n",
"\n",
"       To specify an image file and piece coordinates, include\n",
"       the following:\n",
"\n",
"       IMAGE image_filename\n",
"       XYZ                           [on a line by itself]\n",
"       x  y  z                       [piece coordinates, one line per section]\n",
"        . . .\n",
"\n",
"\n",
"PLUGIN ENVIRONMENT\n",
"       Imod will load special plugin libraries that are in the\n",
"       directory pointed to by the IMOD_PLUGIN_DIR environment\n",
"       variable.  The directories /usr/IMOD/plugins,\n",
"       /usr/local/IMOD/plugins, and /usr/freeware/lib/imodplugs/\n",
"       are loaded by default if they exist.  To write your own\n",
"       plugins, look for the IMOD software development kit on the\n",
"       IMOD home page at http://bio3d.colorado.edu/imod\n",
"\n",
"\n",
"AUTHORS\n",
"       Jim Kremer\n",
"       David Mastronarde\n",
"\n",
"SEE ALSO\n",
"       Viewing programs  imodv, mrcv\n",
"       Model conversion  imod2nff, imod2wmod, imod2synu, wmod2imod\n",
"                         and imod2rib.\n",
"       Image conversion  tomrc, frommrc (convert to/from sgi images)\n",
"                         tif2mrc, raw2mrc.\n",
"       Please email all bug reports to mast@colorado.edu.\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"\n",
"BL3DFS                         2.50                            15\n",
"\n",
"\n",
"",
 NULL};
