include ../configure

all : imodhelp.h

mkargv : mkargv.o
	$(CC) $(CFLAGS) -o mkargv mkargv.o

imodhelp.h : imodhelp mkargv
	./mkargv imodhelp imodhelp.h "Imod_help_text[]"

install	:
	$(CP) $(VCEXEDIR)/3dmod.exe $(INSTBINDIR)
	$(CP) 3dmodbg $(INSTBINDIR)
	$(CP) 3dmodv $(INSTBINDIR)

clean :
