char *Imod_menus_help[] = {
"Imod: Help for Informations Window Menus\n",
"------------------------------------------------------------------------\n",
"The File Menu:\n",
"\tNew   Model    -- Clears current model and creates a new one.\n",
"\tOpen  Model    -- Loads a new model file.\n",
"        Save  Model    -- Saves model file to current file name.\n",
"        Save  Model as -- Saves model file, and prompts for a name.\n",
"\tWrite Model as ---> Writes model to one of the following formats.\n",
"\t\t\tImod - native model format.\n",
"\t\t\tWimp - Used on BL3DFS VAX machine.\n",
"\t\t\tNFF  -\n",
"\t\t\tSynu - San Diego format.\n",
"\tMemory to TIFF -- Saves entire color image from memory to TIFF file.\n"
"\tAbout          -- Prints information about this version of Imod.\n",
"\t----------\n",
"\tQuit           -- Exit dialog.\n",
"\n",
"The Edit Menu:\n",
"\tModel-->\n",
"                Header...   Set:  whether model will be drawn or not (t),\n",
"                                  the Z scale for viewing the model,\n",
"                                  the resolution, or spacing between points,\n",
"                                  the pixel size in real units (nm, um, mm).\n"
"                Offsets...  Adjust offsets to x, y & z model data.\n",
"                Clean       Delete all objects that have no points.\n",
"\n",
"        Object-->\n",
"                New         Create a new object.\n",
"                Delete      Delete current object.\n",
"\t\t-----------\n",
"                Color...    Opens requester for changing object color.\n",
"                Type...     Edit Object type.\n",
"\t\tGo To...    Go to a different object.\n",
"\t\tMove..\t    Move all contours in object to a different object.\n",
"\t\tInfo\t    Print total volume and surface area of object.\n",
"\t\tClean\t    Delete empty contours from object.\n",
"\n",
"        Surface-->\n",
"                New         Creates a new contour on a new surface. (N)\n",
"\t\tGo To...    Go to a different surface.\n",
"                Move...     Move contours to new surfaces within object.\n",
"\n",
"        Contour-->\n",
"                New      Creates a new contour.   (n)\n",
"                Delete   Deletes current contour  (D)\n",
"                Move...  Move current contour to a new object #.\n",
"                Sort     Sort all contours in object by their Z values.\n",
"                Auto...  Open window for making new contours using threshold.\n",
"                Type...  Select a surface, time index or label for a contour.\n",
"\t\tGo To... Go to a different contour.\n",
"\t\tInfo     Print area and length of current contour.\n",
"\t\tBreak... Break a contour into two contours.\n",
"\t\tFix by Z Break a closed contour into separate ones by Z.\n"
"\t\tJoin...\t Join two contours together.\n",
"\t\tInvert\t Invert the order of points in the current contour.\n",
"\t\tCopy...\t Copy contours to new object or new Z level\n",
"\t\tLoopback Add duplicate points in reverse to make a complex cap.\n" 
"\t\tFill in  Add point at each Z level skipped by existing points.\n" 
"\n",
"        Point-->\n",
"                Delete        Delete Current point. (Delete)\n",
"                Sort by dist  Sort points in contour by interpoint distance.\n",
"                Sort by Z     Sort points in contour by their Z values.\n",
"                Distance      Show distance between model points.\n",
"                Value         Show current voxel value.\n",
"                Go To...      Go to a different point.\n",
"                Size...       Set size of individual points.\n",
"\n",
"\tImage -->\n",
"\t\tProcess...      Process images by filtering.\n"
"\t\tColormap...     Select image colormap #.\n",
"\t\tReload...       Reload image data with current contrast.\n",
"\t\tFlip            Exchange Y and Z dimensions of the image data.\n",
"\t\tFill Cache      Fill the image cache if there is one.\n",
"\t\tCache Filler... Open window to control cache filling.\n",
"\n",
"\tMovies...\tOpen window to control range and speed of movies.\n",
"\n",
"The Image Menu\n",
"\tGraph\t\tOpen the Image Graph window.\n",
"        Slicer          Open Window showing a sliced view of the\n",
"                        image data. (\\)\n",
"        Tumbler         Opens 3-D project window.\n",
"        Tilt...         Load Extra Tilt Image for viewing.\n",
"        Model View      Opens an imod view window. (v)\n",
"\tZaP\t\tOpens the Zoom and Pan modeling window.\n",
"\tXYZ\t\tOpens the linked xyz window.\n",
"        Pixel View      View pixel values in a grid.\n",
"",
 NULL};
