#!/bin/csh
###########################################################################
# SGI running IRIX 6
#
# $Id$
# Log at end
#

# 
#set glwincdir = /usr/include/X11/GLw
set c_includes =  '-I$(QTDIR)/include'

goto $machine
irix6-32:
set flags = "-32 -mips2 $flags"
set fallback = "$flags"
echo "MAKELIB = ld -32 -mips2 -shared -all -o " >> $configure
echo 'LDFLAGS = -32 -mips2 -L$(LIBDIR)  -woff 84'       >> $configure
set usfftdir = $source_dir/USFFTlib/sgi
set xplax = noplax.o
goto irix5

irix6:
irix6-n32:

set fallback = "-32 -mips2 $flags"
set flags = "-n32 -mips3 $flags"
echo "MAKELIB = ld -n32 -mips3 -shared -all -o " >> $configure
echo 'LDFLAGS = -n32 -mips3 -L$(LIBDIR) -woff 84'       >> $configure
if ($inst_dir != default) then
	set  inst_lib_dir = $inst_dir/lib32/ 
else
	set  inst_lib_dir = $source_dir/lib32/ 
endif
set lib_dir         = $source_dir/buildlib32/
#
#   default is to assume tifflib for n32, not for old 32
#
if ($tifflibs == default) set tifflibs = true

set usfftdir = $source_dir/USFFTlib/sgi32

goto irix5

###########################################################################
# SGI running IRIX 5.3, or the rest of items for IRIX 6
#
irix5:
if ($compiler == gnu) then
	echo "CC      = gcc"  >> $configure
	echo "CXX     = g++"  >> $configure
        set fcomp = "g77"
	# DNM 11/10/01: Other flags below need to be fixed for this probably!
else
	echo "CC      = cc"  >> $configure
	echo "CXX     = CC"  >> $configure
        set fcomp = "f77"
endif

# Watch out for the tab in the build rule

cat << EOF >> $configure
.SUFFIXES: .cpp
.cpp.o:
	\$(CXX) -c \$(CXXFLAGS) -o \$@ \$<

CP      = cp
FIND    = find
EOF

if ($machine == irix5) then
	echo 'LDFLAGS = -L$(LIBDIR) '       >> $configure
endif

if ($shared_libs != false) then
	echo "AR      = ld"                 >> $configure
	echo "ARFLAGS = $flags -shared -all -o "    >> $configure
	echo "LIBEXT  = so"                 >> $configure
else
	echo "AR      = ar"                 >> $configure
	echo "ARFLAGS = clq "                >> $configure
	echo 'MAKELIB = $(AR) $(ARFLAGS)'   >> $configure
	echo "LIBEXT  = a"                  >> $configure
endif
echo "RANLIB    = true"                     >> $configure
echo "MAKELIBSO = ld $flags -shared -all -o "       >> $configure
echo 'MAKELIBCPP = $(MAKELIB)'              >> $configure

if ($debug == true) then
#	echo "CLIBS   = -lmalloc_cv -lm -lc" >> $configure
#	echo "CLIBS   = -lfpe -lm -lc"       >> $configure
	echo "CLIBS   = -lm -lc"             >> $configure
else
	echo "CLIBS   = -lm -lc"             >> $configure
endif

echo 'LIBS     = $(CLIBS)'                              >> $configure
echo 'FORTCLIBS = $(CLIBS)'                              >> $configure

echo "XLIBS      = -lXm -lXt -lX11 -lXext -lPW" >> $configure
echo "IMLIBS     = -lhvem -lmrcim -lifft -lcfshr" >> $configure

echo 'IMODCC    = $(CC)'  >> $configure
echo  'MAKEF77PLUGIN  = ld $(LDFLAGS) -shared -all -lftn -o'  >> $configure
echo 'FLCC      = $(CC)'  >> $configure
echo 'F77LIBS   = '                  >> $configure
#echo "F77LIBS      = -lF77 -lU77 -lI77 -lisam" >> $configure
echo 'LIBTRACKDEF   = -lftn'                  >> $configure

# Tell Blendmont how big record items are
#
echo "      parameter (nbytes_recl_item=4)" >! $endian_dir/recl_bytes.inc

# For Qt 3.3 (3.2?), need to post message twice
#
echo '#define SENDEVENT_RETRY_HACK 0' >> $hconfigure

set foptimization = $optimization
if ($debug == true) then
	set optimization = "-g -fullwarn -woff 1174,1552,3201"
	set foptimization = "-g -woff 2274"
else
	set optimization = "-O2 -woff 1174,1552"
endif

# 4/8/04: Use intermediate variables to simplify all the defines that are needed
#
set cflags = "$optimization $defines $include_flags $c_includes"
set fflags = "$foptimization $defines $include_flags -extend_source"

echo "CFLAGS   = $flags $cflags" >> $configure
echo "CXXFLAGS = $flags $cflags" >> $configure
echo "FFLAGS   = $flags $fflags" >> $configure
echo "NOOPFFLAGS = $flags $fflags -O0" >> $configure

# 4/8/04: Add flags for building libraries
#
echo "LIBCFLAGS  = $flags $cflags" >> $configure
echo "LIBFFLAGS  = $flags $fflags" >> $configure

# Pick whose floats the fortran code can swap
if ($swap_ieee == true) then
    echo "#define SWAP_IEEE_FLOATS"                 >> $hconfigure
endif

#
# Use a workaround when window managers won't do StaysOnTop reliably
#
echo '#define STAY_ON_TOP_HACK' >> $hconfigure

#
# Do not use multiple threads in plax programs; other thread stuff seems OK
#
echo '#define QTPLAX_NO_THREAD' >> $hconfigure

#
# Set this because ordinary geometry saving method makes windows walk up and
# to the left
#
echo '#define SGI_GEOMETRY_HACK' >> $hconfigure


# Build tilt from Fortran subroutines, skip extra libraries, make sgi-specific
echo 'TILTOBJS = bpsumnox.o bpsumxtilt.o bpsumlocal.o' >> $configure
set rgbprogs = "frommrc tomrc mrcv"


# Set up for a dummy tiff library 
set dummytiff = 'nolibtiff.$(LIBEXT)'

#
# Set the switch point include file for the FBP algorithm in Tilt
#
set fbpswitch       = fbpswitch-sgi.inc

#
# Set up things for Qt include files
#
cat << EOF  >! $midas_qconf

EOF

cat << EOF >! $imod_qconf
SOURCES += linegui.cpp
HEADERS += linegui.h
LIBS += -L$lib_dir -liimod -limesh -limod -ldiaqt -lifft -ltiff -ltrack
LIBS += -lqassistantclient -lm
INCLUDEPATH += .
EOF

#
# Set up to copy qt lib for a distribution, and set name of LD_LIBRARY variable
echo 'QTINSTLIBDIR = qtlib' >> $configure
set ld_lib_var      = LD_LIBRARYN32_PATH
echo 'INSTALL_FILES = IMOD-sgi.csh sgi.cshrc IMOD-sgi.sh sgi.bashrc' >> $configure
if ($distname == "") set distname = _irix6.5


#  $Log$
#  Revision 3.34  2007/09/18 05:10:37  mast
#  Changes for ctfplotter and qt stuff
#
#  Revision 3.33  2006/09/12 16:34:54  mast
#  Added mesh library for 3dmod
#
#  Revision 3.32  2005/12/09 06:02:33  mast
#  Added extend_source flag for fortran
#
#  Revision 3.31  2005/07/06 21:12:32  mast
#  Removed fallbacks
#
#  Revision 3.30  2005/06/27 19:39:41  mast
#  Needed to set sendevent retry hack 0
#
#  Revision 3.29  2005/02/28 22:07:51  mast
#  Added record item length since this is now the oddball
#
#  Revision 3.28  2005/01/17 19:33:04  mast
#  Remove shell variable from configure
#
#  Revision 3.27  2004/11/22 00:20:11  mast
#  Added Qt assistant
#
#  Revision 3.26  2004/11/09 17:52:56  mast
#  Start using multithreaded library
#
#  Revision 3.25  2004/11/07 23:07:56  mast
#  Added libifft to 3dmod build
#
#  Revision 3.24  2004/06/04 17:38:43  mast
#  Added definition of LIBTRACKDEF to get -lftn into libtrack.so build
#
#  Revision 3.23  2004/04/22 02:30:19  mast
#  Added sgi.bashrc to INSTALL_FILES
#
#  Revision 3.22  2004/04/08 17:01:18  mast
#  Changes for separate library-building flags
#
#  Revision 3.21  2004/01/29 04:22:27  rickg
#  added IMOD-sgi.sh to INSTALL_FILES
#
#  Revision 3.20  2004/01/27 05:17:04  mast
#  Add INSTALL_FILES and distname settings
#
#  Revision 3.19  2003/12/30 17:40:45  mast
#  Have to put $ in quotes
#
#  Revision 3.18  2003/12/30 17:28:03  mast
#  only irix needs a notifflib
#
#  Revision 3.17  2003/11/01 16:38:58  mast
#  put libiimod before libimod
#
#  Revision 3.16  2003/10/25 16:46:45  mast
#  changes for moving line tracker to special module
#
#  Revision 3.15  2003/10/24 19:52:40  mast
#  changes after windows work, plus donot add plax in o32lib build
#
#  Revision 3.14  2003/10/24 04:18:43  mast
#  changes for WIndows/Intel compilation
#
#  Revision 3.13  2003/09/24 23:06:05  mast
#  reinstate qtplax!
#
#  Revision 3.12  2003/09/24 20:40:48  mast
#  Back off from using Qt plax and go back to X plax routines
#
#  Revision 3.11  2003/09/24 17:31:39  mast
#  Add geometry define
#
#  Revision 3.10  2003/08/29 16:58:24  mast
#  Sepcify no threading for Plax applications
#
#  Revision 3.9  2003/08/25 19:48:16  mast
#  *** empty log message ***
#
#  Revision 3.8  2003/05/08 20:46:04  mast
#  *** empty log message ***
#
#  Revision 3.7  2003/05/08 20:23:27  mast
#  *** empty log message ***
#
#  Revision 3.6  2003/05/08 20:22:32  mast
#  *** empty log message ***
#
#  Revision 3.5  2003/03/28 23:53:41  mast
#  new version of Plax
#
#  Revision 3.4  2003/03/18 19:27:08  mast
#  Add hack definition for keeping window on top
#
#  Revision 3.3  2003/02/10 20:58:00  mast
#  *** empty log message ***
#
#  Revision 3.2.2.9  2003/01/30 05:50:02  mast
#  *** empty log message ***
#
#  Revision 3.2.2.8  2003/01/27 00:38:37  mast
#  fine-tuning the build after pure Qt imod
#
#  Revision 3.2.2.7  2002/12/06 22:04:56  mast
#  *** empty log message ***
#
#  Revision 3.2.2.6  2002/12/06 17:16:41  mast
#  *** empty log message ***
#
#  Revision 3.2.2.5  2002/12/06 05:18:42  mast
#  *** empty log message ***
#
#  Revision 3.2.2.4  2002/12/05 19:48:32  mast
#  *** empty log message ***
#
#  Revision 3.2.2.3  2002/12/05 19:04:19  mast
#  *** empty log message ***
#
#  Revision 3.2.2.2  2002/12/05 18:57:00  mast
#  *** empty log message ***
#
#  Revision 3.2.2.1  2002/12/05 18:10:18  mast
#  *** empty log message ***
#
#  Revision 3.2  2002/07/26 19:15:27  mast
#  *** empty log message ***
#
#  Revision 3.1  2002/07/19 01:23:56  rickg
#  Changed include directory search path to explicitly use /usr/include/X11/GLw
#  so that GLw include are picked up without preceeding path arguments in the
#  source code.
#
#  Revision 3.0  2001/11/29 18:10:59  rickg
#  *** empty log message ***
#
#  Revision 1.2  2001/11/28 15:41:50  mast
#  Changed instdir to inst_dir
#
