include ../../configure

FFLAGS = $(LIBFFLAGS)

OBJS = degtrig.$(OBJEXT)

all: $(OBJS)

clean:
	$(FIND) . -type f -name "*.o*" -exec rm "{}" \;
	$(FIND) . -type f -name "*~" -exec rm "{}" \;
	$(FIND) . -type f -name "#*#" -exec rm "{}" \;
