#!/bin/csh -f

# Script to take the adpStub and insert the 3dmod help pages and the man
# pages as subsections.
#
#  $Author$
#
#  $Date$
#
#  $Revision$
#
#  $Log$
#  Revision 3.1  2006/06/18 23:44:24  mast
#  Added to package
#

set instext1 = "INSERT 3DMOD.ADP"
set instext2 = "INSERT MAN PAGES"
set adpout = IMOD.adp
set adpin = adpStub
set instdir = .
if ($#argv > 0) then
    set instdir = $argv[1]/html
endif

awk "NR==1, /$instext1/" $adpin | grep -v "INSERT" >! $adpout
awk '/<DCF/,/<\/DCF/' 3dmodHelp/3dmod.adp | \
  sed -e '/DCF/d' -e '/\.\//s//\.\/3dmodHelp\//' >> $adpout
awk "/$instext1/, /$instext2/" $adpin | grep -v "INSERT" >> $adpout

foreach i ($instdir/man/*.html)
set file = $i:r:t
cat <<EOF >> $adpout
    <section ref ="./man/$file.html" title="$file"/>
EOF
end

awk "/$instext2/, /GobbledyGook/" $adpin | grep -v "INSERT" >> $adpout
