#! /bin/csh -f
# A simple script to start imod and imodv the background, a workaround to
# problems with forking the process on the PC
set pn = $0
if ($pn:t == bgimodv) then
	imodv $* &
else
	imod $* &
endif
