#!/bin/sh
if [ -e "${IMOD_DIR}/bin/setlibpath" ]; then
  . "${IMOD_DIR}/bin/setlibpath"
fi
if [ ! -z "$IMOD_QTLIBDIR" ] ; then
    export PATH="${IMOD_QTLIBDIR}:$PATH"
fi
assistant_adp -profile $IMOD_DIR/html/IMOD.adp -file $IMOD_DIR/html/index.html&
