#!/bin/csh -f
# A script to call a postscript previewer.  Try gv first (standard on early
# Redhat 7?), then xpsview for SGI, then gs, which is not as good as gv

set test = `which gv`
if (! $status) then
    gv -noanti $*
    exit 0
endif

set test = `which xpsview`
if (! $status) then
    xpsview $*
    exit 0
endif

set test = `which gs`
if (! $status) then
    echo " "
    echo "TYPE CTRL C TO EXIT THE GS PREVIEWER"
    echo
    gs $*
    exit 0
endif

echo "imodpsview cannot find a PostScript previewer on your system"
echo "If you have one, modify $IMOD_DIR/bin/imodpsview to call it"
