#! /bin/csh -f

#  $Author$
#
#  $Date$
#
#  $Revision$
#
#  $Log$
#  Revision 3.11  2003/12/27 21:37:24  mast
#  needed to keep path-setting
#
#  Revision 3.10  2003/12/25 00:33:51  mast
#  Discontinued!
#
#  Revision 3.9  2003/11/18 19:22:16  mast
#  run newstack directly instead of with csh; Mac change fails on Windows
#
#  Revision 3.8  2003/11/13 19:43:02  mast
#  Needed to run csh with -f flag
#
#  Revision 3.7  2003/10/24 02:14:00  mast
#  source settmpdir to get tmpdir, better for Windows
#
#  Revision 3.6  2003/07/10 23:41:49  mast
#  Added ability to specify multiple input files
#
#  Revision 3.5  2003/06/20 20:02:46  mast
#  Let tmpdir be defined and fall back to /tmp if /usr/tmp does not exist
#
#  Revision 3.4  2003/03/14 02:00:28  mast
#  Added linear interpolation option
#
#  Revision 3.3  2002/12/10 18:11:08  mast
#  Implemented combinations of transforming, rotating, and scaling
#
#  Revision 3.2  2002/11/14 20:18:41  mast
#  Made it exit with an error if newstack does
#

if ($#argv == 0) then
cat <<EOF
Newst has been retired - Newstack will now accept all newst options directly.

Here is a quick summary of the old options; use "newstack -h" for full list

Usage: newstack [options] input.file(s) output.file
  options:  -se[cs] section_list         (default is entire file)
            -si[ze] X,Y
            -m[ode] new_mode
            -o[ffset] dX,dY              (single offset used for whole file)
            -x[form] transform_file
            -l[inear]                    (transform with linear interpolation)
            -e[xpand] expansion_factor   (>1 to expand, <1 to squeeze)
            -r[otate] rotation_angle     (degrees, counterclockwise positive)
            -c[ontrast] black,white      (scale to black/white levels)
            -f[loat] option  (0=none, 1=range, 2=mean/SD, 3 = shift to mean
EOF
exit 0
endif

if ($?IMOD_DIR) then
    setenv PATH "$IMOD_DIR/bin:$PATH"
endif

newstack $*
if ($status) exit 1
