#! /bin/csh -f
# patchcrawl3d - to get local 3d cross-correlations between two volumes at
# a grid of positions.
#
#  $Author$
#
#  $Date$
#
#  $Revision$
#
#  $Log$

if ($#argv < 16 || $#argv > 20) then
cat <<EOCAT
Usage: 
patchcrawl3d  XSIZE YSIZE ZSIZE  NX NY NZ  XLO XHI YLO YHI ZLO ZHI  MAX_SHIFT \
       FILEA FILEB OUTPUT_FILE [TRANSFORM_FILE ORIGINAL_FILEB BORDERS] \
       [BOUNDARY_MODEL]
Finds the displacement of the volume in FILEB relative to the volume in FILEA,
 in a series of local volumes of size XSIZE by YSIZE by ZSIZE,
 at grid positions determined by:
   NX, NY, NZ: number of positions in X, Y and Z
   XLO, XHI, YLO, YHI, ZLO, ZHI: minimum and maximum coordinates of the block
       from which local volumes will be extracted 
 MAX_SHIFT sets the maximum displacement that will be determined by local 
   search rather than FFT-based cross-correlation
 It places the list of coordinates and displacements in OUTPUT_FILE
EOCAT
exit 1
endif
set tmpdir = /usr/tmp
set modelfile = ""
if ($?IMOD_DIR) set path = ($IMOD_DIR/bin $path)

@ nxl = $1; shift
@ nyl = $1; shift
@ nzl = $1; shift
@ nx = $1; shift
@ ny = $1; shift
@ nz = $1; shift
@ xbl = $1 - 1; shift
@ xhi = $1; shift
@ ybl = $1 - 1; shift
@ yhi = $1; shift
@ zbl = $1 - 1; shift
@ zhi = $1; shift
set maxshift = $1; shift
set bsource = ""
set xffile = ""
set srcborders = ""
#
set nxyz =  `header $argv[1] | sed -n '/rows, sections/p'| awk '{print $7, $8, $9}'`
@ nxt = $nxyz[1]
@ nyt = $nxyz[2]
@ nzt = $nxyz[3]

@ xbh = $nxt - $xhi
@ ybh = $nyt - $yhi
@ zbh = $nzt - $zhi

# If argument list is even, the last must be a patch model file
#
if ($#argv == 4 || $#argv == 7) then
    set modelfile = $argv[$#argv]
endif

# If a transform file and original volume are entered, pass that on

if ($#argv >= 5) then
    set bsource = $argv[5]
    set xffile = $argv[4]
    set srcborders = $argv[6]
endif
#
@ nxtap = ($nxl + 9) / 10
@ nytap = ($nyl + 9) / 10
@ nztap = ($nzl + 9) / 10

corrsearch3d <<EOF
$argv[1]
$argv[2]
$argv[3]
patchtmp.$$
$modelfile
$nxl,$nyl,$nzl
$nx,$ny,$nz
$xbl,$xbh,$ybl,$ybh,$zbl,$zbh
$nxtap,$nytap,$nztap
$maxshift
$bsource
$xffile
$srcborders
EOF
if (-e patchtmp.$$) \rm patchtmp.$$
