#!/bin/bash
# A simple wrapper to run a python script against the python on the path
# and get a PID out for Etomo if -P is given before the script name
#
#  $Id$
#
#  $Log$
#  Revision 3.2  2006/09/26 22:19:44  mast
#  Switched to sh which can preserve spaces
#
#  Revision 3.1  2006/09/23 17:47:53  mast
#  Added to package
#
#
if [ $# -lt 1 ] ; then
    exit 1
fi
if [ "$1" == "-P" ] ; then
    echo2 "Shell PID: $$"
    shift
fi
if [ $# -lt 1 ] ; then
    exit 1
fi
if [ -z "$IMOD_DIR" ]; then
    echo "ERROR: runpyscript - environment variable IMOD_DIR is not defined"
    exit 1
fi
prog="$1"
shift
python -u "$IMOD_DIR/bin/$prog" "$@"
