#!/bin/csh -f
# sampletilt - makes a tilt sample using the current tilt.com
#
#  $Id$
#
#  $Log$
#  Revision 3.3  2007/12/06 22:40:37  mast
#  Knock out adjustorigin entry to be conservative
#
#  Revision 3.2  2006/09/19 19:13:32  mast
#  Even the shortest script can have a stupid bug
#
#  Revision 3.1  2006/09/18 21:25:47  mast
#  Added to allow easier transition to python
#
#
nohup

if ($#argv != 6) then
    echo "ERROR: sampletilt - need 6 params: slice start & end, ystart, set name, rec name, com file name"
    exit 1
endif

set slstart = $argv[1]
set slend = $argv[2]
set ystart = $argv[3]
set setname = $argv[4]
set recname = $argv[5]
set tiltname = $argv[6]

sed -e '/^[$#]/d' -e "/SUBSETSTART.*/s//SUBSETSTART 0 $ystart/" \
 -e "/$setname.*\.rec/s//$recname/" -e '/SLICE/d' -e '/WIDTH/d' \
 -e '/AdjustOrigin/d' -e '/[[:cntrl:]]/s///g' -e '/THICKNESS/a\\
SLICE'" $slstart $slend"' 1\
' $tiltname |tilt
exit $status
