#! /bin/csh -f
if ($?IMOD_DIR) then
    setenv PATH "$IMOD_DIR/bin:$PATH"
endif

if ($#argv == 0) then
cat <<EOF
Xf2xg has been retired - Xftoxg now accepts command-line options
NOTE THAT THE -h OPTION OF XF2XG IS IMPLEMENTED BY -m IN XFTOXG

EOF
xftoxg -h
exit
endif

xftoxg $*
exit $status
