/* THIS FILE IS GENERATED BY SETUP: DO NOT EDIT */
#ifndef IMOD_CONFIG_INCLUDED
#define IMOD_CONFIG_INCLUDED
#define VERSION              300
#define VERSION_NAME "3.0.0"
#define COPYRIGHT_YEARS "1994-2003"
#define LAB_NAME1 "Boulder Laboratory for 3-Dimensional"
#define LAB_NAME2 "Electron Microscopy of Cells"
#ifndef LITTLE_ENDIAN
#define LITTLE_ENDIAN
#endif
#define SWAP_IEEE_FLOATS
#define NOTIFFLIBS
#define NO_SYS_TIMES
#define NO_IMOD_FORK
#define CLIPBOARD_TIMER_HACK 100
typedef char b3dByte;
typedef unsigned char b3dUByte;
typedef short int b3dInt16;
typedef unsigned short int b3dUInt16;
typedef int b3dInt32;
typedef unsigned int b3dUInt32;
typedef float b3dFloat;
#endif
