# Makefile for making plugins.
# An old version of beadfix is retained for testing the build, but there is no 
# install for this.  To test the plugin, do an install manually from the 
# beadfix directory

# New actual plugins would be added to the install line

all : ALWAYS
	cd beadfix   ;    $(MAKE) $@

install : 

clean : ALWAYS
	cd beadfix   ;    $(MAKE) $@

ALWAYS:


