
all : ALWAYS
	cd 4dPlugs   ;    $(MAKE) $@
	cd beadfix   ;    $(MAKE) $@
	cd linetrack ;    $(MAKE) $@

install : ALWAYS
	cd 4dPlugs   ;    $(MAKE) $@
	cd beadfix   ;    $(MAKE) $@
	cd linetrack ;    $(MAKE) $@

clean : ALWAYS
	cd 4dPlugs   ;    $(MAKE) $@
	cd beadfix   ;    $(MAKE) $@
	cd linetrack ;    $(MAKE) $@

ALWAYS:


